var Kinetic={};(function(){Kinetic.version='4.2.0';Kinetic.Filters={};Kinetic.Plugins={};Kinetic.Global={stages:[],idCounter:0,tempNodes:{},shapes:{},warn:function(str){if(window.console&&console.warn){console.warn('Kinetic warning: '+str);}},extend:function(c1,c2){ for(var key in c2.prototype){if(!(key in c1.prototype)){c1.prototype[key]=c2.prototype[key];}}},_pullNodes:function(stage){var tempNodes=this.tempNodes;for(var key in tempNodes){var node=tempNodes[key];if(node.getStage()!==undefined&&node.getStage()._id===stage._id){stage._addId(node);stage._addName(node);this._removeTempNode(node);}}},_addTempNode:function(node){this.tempNodes[node._id]=node;},_removeTempNode:function(node){delete this.tempNodes[node._id];}};})();(function(root,factory){if(typeof exports==='object'){module.exports=factory();}
else if(typeof define==='function'&&define.amd){define(factory);}
else{root.returnExports=factory();}}(this,function(){return Kinetic;}));(function(){Kinetic.Type={_isElement:function(obj){return!!(obj&&obj.nodeType==1);},_isFunction:function(obj){return!!(obj&&obj.constructor&&obj.call&&obj.apply);},_isObject:function(obj){return(!!obj&&obj.constructor==Object);},_isArray:function(obj){return Object.prototype.toString.call(obj)=='[object Array]';},_isNumber:function(obj){return Object.prototype.toString.call(obj)=='[object Number]';},_isString:function(obj){return Object.prototype.toString.call(obj)=='[object String]';},_hasMethods:function(obj){var names=[];for(var key in obj){if(this._isFunction(obj[key]))
names.push(key);}
return names.length>0;}, _getXY:function(arg){if(this._isNumber(arg)){return{x:arg,y:arg};}
else if(this._isArray(arg)){if(arg.length===1){var val=arg[0];if(this._isNumber(val)){return{x:val,y:val};}
else if(this._isArray(val)){return{x:val[0],y:val[1]};}
else if(this._isObject(val)){return val;}}
else if(arg.length>=2){return{x:arg[0],y:arg[1]};}}
else if(this._isObject(arg)){return arg;}
return{x:0,y:0};},_getSize:function(arg){
if(this._isNumber(arg)){return{width:arg,height:arg};}
else if(this._isArray(arg)){if(arg.length===1){var val=arg[0];if(this._isNumber(val)){return{width:val,height:val};}
else if(this._isArray(val)){if(val.length>=4){return{width:val[2],height:val[3]};}
else if(val.length>=2){return{width:val[0],height:val[1]};}}
else if(this._isObject(val)){return val;}}
else if(arg.length>=4){return{width:arg[2],height:arg[3]
};}
else if(arg.length>=2){return{width:arg[0],height:arg[1]};}}
else if(this._isObject(arg)){return arg;}
return{width:0,height:0};},_getPoints:function(arg){if(arg===undefined){return[];}
if(this._isObject(arg[0])){return arg;}
else{var arr=[];for(var n=0;n<arg.length;n+=2){arr.push({x:arg[n],y:arg[n+1]});}
return arr;}},_getImage:function(arg,callback){if(!arg){callback(null);}
else if(this._isElement(arg)){callback(arg);}
else if(this._isString(arg)){var imageObj=new Image();imageObj.onload=function(){
callback(imageObj);}
imageObj.src=arg;}
else if(arg.data){var canvas=document.createElement('canvas');canvas.width=arg.width;canvas.height=arg.height;var context=canvas.getContext('2d');context.putImageData(arg,0,0);var dataUrl=canvas.toDataURL();var imageObj=new Image();imageObj.onload=function(){callback(imageObj);}
imageObj.src=dataUrl;}
else{callback(null);}},_rgbToHex:function(r,g,b){return((1<<24)+(r<<16)+(g<<8)+b).toString(16).slice(1);},_hexToRgb:function(hex){var bigint=parseInt(hex,16);return{r:(bigint>>16)&255,g:(bigint>>8)&255,b:bigint&255};},_getRandomColorKey:function(){var r=Math.round(Math.random()*255);var g=Math.round(Math.random()*255);var b=Math.round(Math.random()*255);return this._rgbToHex(r,g,b);},_merge:function(o1,o2){var retObj=this._clone(o2);for(var key in o1){if(this._isObject(o1[key])){retObj[key]=this._merge(o1[key],retObj[key]);}
else{retObj[key]=o1[key];}}
return retObj;},_clone:function(obj){var retObj={};for(var key in obj){if(this._isObject(obj[key])){retObj[key]=this._clone(obj[key]);}
else{retObj[key]=obj[key];}}
return retObj;},_degToRad:function(deg){return deg*Math.PI/180;},_radToDeg:function(rad){return rad*180/Math.PI;}};})();(function(){Kinetic.Canvas=function(width,height){this.width=width;this.height=height;this.element= document.createElement('canvas');this.context=this.element.getContext('2d');this.setSize(width||0,height||0);};var canvas=document.createElement('canvas'),context=canvas.getContext('2d'),devicePixelRatio=window.devicePixelRatio||1,backingStoreRatio=context.webkitBackingStorePixelRatio||context.mozBackingStorePixelRatio||context.msBackingStorePixelRatio||context.oBackingStorePixelRatio||context.backingStorePixelRatio||1;Kinetic.Canvas.pixelRatio=devicePixelRatio/backingStoreRatio;Kinetic.Canvas.prototype={clear:function(){var context=this.getContext();var el=this.getElement();context.clearRect(0,0,el.width,el.height);},getElement:function(){return this.element;},getContext:function(){return this.context;},setWidth:function(width){this.width=width;this.element.width=width*Kinetic.Canvas.pixelRatio;this.element.style.width=width+'px';},setHeight:function(height){this.height=height; this.element.height=height*Kinetic.Canvas.pixelRatio;this.element.style.height=height+'px';},getWidth:function(){return this.width;},getHeight:function(){return this.height;},setSize:function(width,height){this.setWidth(width);this.setHeight(height);},toDataURL:function(mimeType,quality){try{return this.element.toDataURL(mimeType,quality);}
catch(e){try{return this.element.toDataURL();}
catch(e){Kinetic.Global.warn('Unable to get data URL. '+e.message)
return '';}}},fill:function(shape){this._fill(shape);},/**/
stroke:function(shape){this._stroke(shape);},fillStroke:function(shape){this._fill(shape);this._stroke(shape,shape.getShadow()&&shape.getFill());},/**/
applyShadow:function(shape,drawFunc){var context=this.context;context.save();this._applyShadow(shape);drawFunc();context.restore();drawFunc();},_applyLineCap:function(shape){var lineCap=shape.getLineCap();if(lineCap){this.context.lineCap=lineCap;}},_applyOpacity:function(shape){var absOpacity=shape.getAbsoluteOpacity();if(absOpacity!==1){this.context.globalAlpha=absOpacity;}},_applyLineJoin:function(shape){var lineJoin=shape.getLineJoin();if(lineJoin){this.context.lineJoin=lineJoin;}},_handlePixelRatio:function(){var pixelRatio=Kinetic.Canvas.pixelRatio;if(pixelRatio!==1){this.getContext().scale(pixelRatio,pixelRatio);}}};Kinetic.SceneCanvas=function(width,height){Kinetic.Canvas.call(this,width,height);};Kinetic.SceneCanvas.prototype={_fill:function(shape,skipShadow){var context=this.context,fill=shape.getFill(),fillType=shape._getFillType(fill),shadow=shape.getShadow();if(fill){context.save();if(!skipShadow&&shadow){this._applyShadow(shape);}
switch(fillType){case 'COLOR': context.fillStyle=fill;context.fill(context);break;case 'PATTERN':if(fill.x||fill.y){context.translate(fill.x||0,fill.y||0);}
if(fill.rotation){context.rotate(fill.rotation);}
if(fill.scale){context.scale(fill.scale.x,fill.scale.y);}
if(fill.offset){context.translate(-1*fill.offset.x,-1*fill.offset.y);}
context.fillStyle=context.createPattern(fill.image,fill.repeat||'repeat');context.fill(context);break;case 'LINEAR_GRADIENT':var s=fill.start;var e=fill.end;var grd=context.createLinearGradient(s.x,s.y,e.x,e.y);var colorStops=fill.colorStops;for(var n=0;n<colorStops.length;n+=2){grd.addColorStop(colorStops[n],colorStops[n+1]);}
context.fillStyle=grd;context.fill(context);break;case 'RADIAL_GRADIENT':var s=fill.start;var e=fill.end;var grd=context.createRadialGradient(s.x,s.y,s.radius,e.x,e.y,e.radius);var colorStops=fill.colorStops;for(var n=0;n<colorStops.length;n+=2){grd.addColorStop(colorStops[n],colorStops[n+1]);}
context.fillStyle=grd;context.fill(context);break;default:context.fillStyle='black';context.fill(context);break;}
context.restore();if(!skipShadow&&shadow&&shadow.opacity){this._fill(shape,true);}}},_stroke:function(shape,skipShadow){var context=this.context,stroke=shape.getStroke(),strokeWidth=shape.getStrokeWidth(),shadow=shape.getShadow(),dashArray=shape.getDashArray();if(stroke||strokeWidth){context.save();this._applyLineCap(shape);if(dashArray){if(context.setLineDash){context.setLineDash(dashArray);}
else{Kinetic.Global.warn('Could not apply dash array because your browser does not support it.');}}
if(!skipShadow&&shadow){this._applyShadow(shape);}
context.lineWidth=strokeWidth||2;context.strokeStyle=stroke||'black';context.stroke(context);context.restore();if(!skipShadow&&shadow&&shadow.opacity){this._stroke(shape,true);}}},_applyShadow:function(shape){var context=this.context,shadow=shape.getShadow();if(shadow){var aa=shape.getAbsoluteOpacity();var color=shadow.color||'black';var blur=shadow.blur||5;var offset=shadow.offset|| {x:0,y:0};if(shadow.opacity){context.globalAlpha=shadow.opacity*aa;}
context.shadowColor=color;context.shadowBlur=blur;context.shadowOffsetX=offset.x;context.shadowOffsetY=offset.y;}}};Kinetic.Global.extend(Kinetic.SceneCanvas,Kinetic.Canvas);Kinetic.HitCanvas=function(width,height){Kinetic.Canvas.call(this,width,height);};Kinetic.HitCanvas.prototype={_fill:function(shape){var context=this.context;context.save();context.fillStyle='#'+shape.colorKey;context.fill(context);context.restore();},_stroke:function(shape){var context=this.context,stroke=shape.getStroke(),strokeWidth=shape.getStrokeWidth();if(stroke||strokeWidth){this._applyLineCap(shape);context.save();context.lineWidth=strokeWidth||2;context.strokeStyle='#'+shape.colorKey;context.stroke(context);context.restore();}}};Kinetic.Global.extend(Kinetic.HitCanvas,Kinetic.Canvas);})();(function(){Kinetic.Tween=function(obj,propFunc,func,begin,finish,duration){this._listeners=[];this.addListener(this);this.obj=obj;this.propFunc=propFunc;this.begin=begin;this._pos=begin;this.setDuration(duration);this.isPlaying=false;this._change=0;this.prevTime=0;this.prevPos=0;this.looping=false;this._time=0;this._position=0;this._startTime=0;this._finish=0;this.name='';this.func=func;this.setFinish(finish);};Kinetic.Tween.prototype={setTime:function(t){this.prevTime=this._time;if(t>this.getDuration()){if(this.looping){this.rewind(t-this._duration);this.update();this.broadcastMessage('onLooped',{target:this,type:'onLooped'});}
else{this._time=this._duration;this.update();this.stop();this.broadcastMessage('onFinished',{target:this,type:'onFinished'});}}
else if(t<0){this.rewind();this.update();}
else{this._time=t;this.update();}},getTime:function(){return this._time;},setDuration:function(d){this._duration=(d===null||d<=0)?100000:d;},getDuration:function(){return this._duration;},setPosition:function(p){this.prevPos=this._pos;this.propFunc(p);this._pos=p;this.broadcastMessage('onChanged',{target:this,type:'onChanged'});},getPosition:function(t){if(t===undefined){t=this._time;}
return this.func(t,this.begin,this._change,this._duration);},setFinish:function(f){this._change=f-this.begin;},getFinish:function(){return this.begin+this._change;},start:function(){this.rewind();this.startEnterFrame();this.broadcastMessage('onStarted',{target:this,type:'onStarted'});},rewind:function(t){this.stop();this._time=(t===undefined)?0:t;this.fixTime();this.update();},fforward:function(){this._time=this._duration;this.fixTime();this.update();},update:function(){this.setPosition(this.getPosition(this._time));},startEnterFrame:function(){this.stopEnterFrame();this.isPlaying=true;this.onEnterFrame();},onEnterFrame:function(){if(this.isPlaying){this.nextFrame();}},nextFrame:function(){this.setTime((this.getTimer()-this._startTime)/1000);},stop:function(){this.stopEnterFrame();this.broadcastMessage('onStopped',{target:this,type:'onStopped'});},stopEnterFrame:function(){this.isPlaying=false;},continueTo:function(finish,duration){this.begin=this._pos;this.setFinish(finish);if(this._duration!==undefined){this.setDuration(duration);}
this.start();},resume:function(){this.fixTime();this.startEnterFrame();this.broadcastMessage('onResumed',{target:this,type:'onResumed'});},yoyo:function(){this.continueTo(this.begin,this._time);},addListener:function(o){this.removeListener(o);return this._listeners.push(o);},removeListener:function(o){var a=this._listeners;var i=a.length;while(i--){if(a[i]==o){a.splice(i,1);return true;}
}
return false;},broadcastMessage:function(){var arr=[];for(var i=0;i<arguments.length;i++){arr.push(arguments[i]);}
var e=arr.shift();var a=this._listeners;var l=a.length;for(var i=0;i<l;i++){if(a[i][e]){a[i][e].apply(a[i],arr);}}},fixTime:function(){this._startTime=this.getTimer()-this._time*1000;},getTimer:function(){return new Date().getTime()-this._time;}};Kinetic.Tweens={'back-ease-in':function(t,b,c,d,a,p){var s=1.70158;return c*(t/=d)*t*((s+1)*t-s)+b;},'back-ease-out':function(t,b,c,d,a,p){var s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},'back-ease-in-out':function(t,b,c,d,a,p){var s=1.70158;if((t/=d/2)<1){return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;}
return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;},'elastic-ease-in':function(t,b,c,d,a,p){var s=0;if(t===0){return b;}
if((t/=d)==1){return b+c;}
if(!p){p=d*0.3;}
if(!a||a<Math.abs(c)){a=c;s=p/4;}
else{s=p/(2*Math.PI)*Math.asin(c/a);}
return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},'elastic-ease-out':function(t,b,c,d,a,p){var s=0;if(t===0){return b;}
if((t/=d)==1){return b+c;}
if(!p){p=d*0.3;}
if(!a||a<Math.abs(c)){a=c;s=p/4;}
else{s=p/(2*Math.PI)*Math.asin(c/a);}
return(a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b);},'elastic-ease-in-out':function(t,b,c,d,a,p){var s=0;if(t===0){return b;}
if((t/=d/2)==2){return b+c;}
if(!p){p=d*(0.3*1.5);}
if(!a||a<Math.abs(c)){a=c;s=p/4;}
else{s=p/(2*Math.PI)*Math.asin(c/a);}
if(t<1){return-0.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;}
return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*0.5+c+b;},'bounce-ease-out':function(t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}
else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+0.75)+b;}
else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+0.9375)+b;}
else{return c*(7.5625*(t-=(2.625/2.75))*t+0.984375)+b;}},'bounce-ease-in':function(t,b,c,d){return c-Kinetic.Tweens['bounce-ease-out'](d-t,0,c,d)+b;},'bounce-ease-in-out':function(t,b,c,d){if(t<d/2){return Kinetic.Tweens['bounce-ease-in'](t*2,0,c,d)*0.5+b;}
else{return Kinetic.Tweens['bounce-ease-out'](t*2-d,0,c,d)*0.5+c*0.5+b;}},'ease-in':function(t,b,c,d){return c*(t/=d)*t+b;},'ease-out':function(t,b,c,d){return-c*(t/=d)*(t-2)+b;},'ease-in-out':function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t+b;}
return-c/2*((--t)*(t-2)-1)+b;},'strong-ease-in':function(t,b,c,d){return c*(t/=d)*t*t*t*t+b;},'strong-ease-out':function(t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b;},'strong-ease-in-out':function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t*t*t*t+b;}
return c/2*((t-=2)*t*t*t*t+2)+b;},'linear':function(t,b,c,d){return c*t/d+b;}};})();(function(){Kinetic.Transform=function(){this.m=[1,0,0,1,0,0];}
Kinetic.Transform.prototype={translate:function(x,y){this.m[4]+=this.m[0]*x+this.m[2]*y;this.m[5]+=this.m[1]*x+this.m[3]*y;},scale:function(sx,sy){this.m[0]*=sx;this.m[1]*=sx;this.m[2]*=sy;this.m[3]*=sy;},/**/
rotate:function(rad){var c=Math.cos(rad);var s=Math.sin(rad);var m11=this.m[0]*c+this.m[2]*s;var m12=this.m[1]*c+this.m[3]*s;var m21=this.m[0]*-s+this.m[2]*c;var m22=this.m[1]*-s+this.m[3]*c;this.m[0]=m11;this.m[1]=m12;this.m[2]=m21;this.m[3]=m22;},getTranslation:function(){return{x:this.m[4],y:this.m[5]};},
multiply:function(matrix){var m11=this.m[0]*matrix.m[0]+this.m[2]*matrix.m[1];var m12=this.m[1]*matrix.m[0]+this.m[3]*matrix.m[1];var m21=this.m[0]*matrix.m[2]+this.m[2]*matrix.m[3];var m22=this.m[1]*matrix.m[2]+this.m[3]*matrix.m[3];var dx=this.m[0]*matrix.m[4]+this.m[2]*matrix.m[5]+this.m[4];var dy=this.m[1]*matrix.m[4]+this.m[3]*matrix.m[5]+this.m[5];this.m[0]=m11;this.m[1]=m12;this.m[2]=m21;this.m[3]=m22;this.m[4]=dx;this.m[5]=dy;},invert:function(){var d=1/(this.m[0]*this.m[3]-this.m[1]*this.m[2]);var m0=this.m[3]*d;var m1=-this.m[1]*d;var m2=-this.m[2]*d;var m3=this.m[0]*d;var m4=d*(this.m[2]*this.m[5]-this.m[3]*this.m[4]);var m5=d*(this.m[1]*this.m[4]-this.m[0]*this.m[5]);this.m[0]=m0;this.m[1]=m1;this.m[2]=m2;this.m[3]=m3;this.m[4]=m4;this.m[5]=m5;},getMatrix:function(){return this.m;}};})();(function(){Kinetic.Collection=function(){var args=[].slice.call(arguments),length=args.length,i=0;this.length=length;for(;i<length;i++){this[i]=args[i];}
return this;}
Kinetic.Collection.prototype =new Array();Kinetic.Collection.prototype.apply=function(method){args=[].slice.call(arguments);args.shift();for(var n=0;n<this.length;n++){if(Kinetic.Type._isFunction(this[n][method])){this[n][method].apply(this[n],args);}}};Kinetic.Collection.prototype.each=function(func){for(var n=0;n<this.length;n++){func.call(this[n],n,this[n]);}};})();(function(){Kinetic.Filters.Grayscale=function(imageData,config){var data=imageData.data;for(var i=0;i<data.length;i+=4){var brightness=0.34*data[i]+0.5*data[i+1]+0.16*data[i+2];data[i]=brightness;data[i+1]=brightness;data[i+2]=brightness;}};})();(function(){Kinetic.Filters.Brighten=function(imageData,config){var brightness=config.val||0;var data=imageData.data;for(var i=0;i<data.length;i+=4){ data[i]+=brightness;data[i+1]+=brightness;data[i+2]+=brightness;}};})();(function(){Kinetic.Filters.Invert=function(imageData,config){var data=imageData.data;for(var i=0;i<data.length;i+=4){data[i]=255-data[i];data[i+1]=255-data[i+1];data[i+2]=255-data[i+2];}};})();(function(){Kinetic.Animation=function(func,node){this.func=func;this.node=node;this.id=Kinetic.Animation.animIdCounter++;this.frame={time:0,timeDiff:0,lastTime:new Date().getTime()};};Kinetic.Animation.prototype={start:function(){this.stop();this.frame.timeDiff=0;this.frame.lastTime=new Date().getTime();Kinetic.Animation._addAnimation(this);Kinetic.Animation._handleAnimation();},/**/
stop:function(){Kinetic.Animation._removeAnimation(this);},_updateFrameObject:function(){var time=new Date().getTime();this.frame.timeDiff=time-this.frame.lastTime;this.frame.lastTime=time;this.frame.time+=this.frame.timeDiff;this.frame.frameRate=1000/this.frame.timeDiff;}};Kinetic.Animation.animations=[];Kinetic.Animation.animIdCounter=0;Kinetic.Animation.animRunning=false;Kinetic.Animation.fixedRequestAnimFrame=function(callback){window.setTimeout(callback,1000/60);};Kinetic.Animation._addAnimation=function(anim){this.animations.push(anim);};Kinetic.Animation._removeAnimation=function(anim){var id=anim.id;var animations=this.animations;for(var n=0;n<animations.length;n++){if(animations[n].id===id){this.animations.splice(n,1);break;}}};Kinetic.Animation._runFrames=function(){var nodes={};for(var n=0;n<this.animations.length;n++){var anim=this.animations[n];anim._updateFrameObject();if(anim.node&&anim.node._id!==undefined){nodes[anim.node._id]=anim.node;}
if(anim.func){anim.func(anim.frame);}}
for(var key in nodes){nodes[key].draw();}};Kinetic.Animation._animationLoop=function(){if(this.animations.length>0){this._runFrames();var that=this;Kinetic.Animation.requestAnimFrame(function(){that._animationLoop();});}
else{this.animRunning=false;}};Kinetic.Animation._handleAnimation=function(){var that=this;if(!this.animRunning){this.animRunning=true;that._animationLoop();}};Kinetic.Animation.requestAnimFrame=function(callback){var raf=Kinetic.DD&&Kinetic.DD.moving?this.fixedRequestAnimFrame:window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||Kinetic.Animation.fixedRequestAnimFrame;raf(callback);};})();(function(){Kinetic.Node=function(config){this._nodeInit(config);};Kinetic.Node.prototype={_nodeInit:function(config){this.defaultNodeAttrs={visible:true,listening:true,name:undefined,opacity:1,x:0,y:0,scale:{x:1,y:1},rotation:0,offset:{x:0,y:0}, draggable:false};this.setDefaultAttrs(this.defaultNodeAttrs);this.eventListeners={};this.setAttrs(config);var that=this;this.on('idChange.kinetic',function(evt){var stage=that.getStage();if(stage){stage._removeId(evt.oldVal);stage._addId(that);}});this.on('nameChange.kinetic',function(evt){var stage=that.getStage();if(stage){stage._removeName(evt.oldVal,that._id);stage._addName(that);}});},on:function(typesStr,handler){var types=typesStr.split(' ');var len=types.length;for(var n=0;n<len;n++){var type=types[n];var event=type;var parts= event.split('.');var baseEvent=parts[0];var name=parts.length>1?parts[1]:'';if(!this.eventListeners[baseEvent]){this.eventListeners[baseEvent]=[];}
this.eventListeners[baseEvent].push({name:name,handler:handler});}},/**/
off:function(typesStr){var types=typesStr.split(' ');var len=types.length;for(var n=0;n<len;n++){var type=types[n];var event=type;var parts=event.split('.');var baseEvent=parts[0];if(parts.length>1){if(baseEvent){if(this.eventListeners[baseEvent]){this._off(baseEvent,parts[1]);}}
else{for(var type in this.eventListeners){this._off(type,parts[1]);}}}
else{delete this.eventListeners[baseEvent];}}},remove:function(){var parent=this.getParent();if(parent&&this.index!==undefined&&parent.children[this.index]._id==this._id){var stage=parent.getStage();if(stage){stage._removeId(this.getId());stage._removeName(this.getName(),this._id);}
Kinetic.Global._removeTempNode(this);parent.children.splice(this.index,1);parent._setChildrenIndices();var dd=Kinetic.DD;if(dd&&dd.node&&dd.node._id===this._id){delete Kinetic.DD.node;}
while(this.children&&this.children.length>0){this.children[0].remove();}
delete this.parent;}},getAttrs:function(){return this.attrs;},setDefaultAttrs:function(config){if(this.attrs===undefined){this.attrs={};}
if(config){for(var key in config){if(this.attrs[key]===undefined){this.attrs[key]=config[key];}}}},setAttrs:function(config){if(config){for(var key in config){var method='set'+key.charAt(0).toUpperCase()+key.slice(1);if(Kinetic.Type._isFunction(this[method])){this[method](config[key]);}
else{this.setAttr(key,config[key]);}}}},getVisible:function(){var visible=this.attrs.visible,parent=this.getParent();if(visible&&parent&&!parent.getVisible()){return false;}
return visible;},getListening:function(){var listening=this.attrs.listening,parent=this.getParent();if(listening&&parent&&!parent.getListening()){return false;}
return listening;},show:function(){this.setVisible(true);},hide:function(){this.setVisible(false);},getZIndex:function(){return this.index;},getAbsoluteZIndex:function(){var level=this.getLevel();var stage=this.getStage();var that=this;var index=0;function addChildren(children){ var nodes=[];var len=children.length;for(var n=0;n<len;n++){var child=children[n];index++;if(child.nodeType!=='Shape'){nodes=nodes.concat(child.getChildren());}
if(child._id===that._id){n=len;}}
if(nodes.length>0&&nodes[0].getLevel()<=level){addChildren(nodes);}}
if(that.nodeType!=='Stage'){addChildren(that.getStage().getChildren());}
return index;},getLevel:function(){var level=0;var parent=this.parent;while(parent){level++;parent=parent.parent;}
return level;},/**/
setPosition:function(){var pos=Kinetic.Type._getXY([].slice.call(arguments));this.setAttr('x',pos.x);this.setAttr('y',pos.y);},getPosition:function(){var attrs=this.attrs;return{x:attrs.x,y:attrs.y};},getAbsolutePosition:function(){var trans=this.getAbsoluteTransform();var o=this.getOffset();trans.translate(o.x,o.y);return trans.getTranslation();},setAbsolutePosition:function(){var pos=Kinetic.Type._getXY([].slice.call(arguments));var trans=this._clearTransform();this.attrs.x=trans.x;this.attrs.y=trans.y;delete trans.x;delete trans.y;var it=this.getAbsoluteTransform();it.invert();it.translate(pos.x,pos.y);pos={x:this.attrs.x+it.getTranslation().x,y:this.attrs.y+it.getTranslation().y};this.setPosition(pos.x,pos.y);this._setTransform(trans);},move:function(){var pos=Kinetic.Type._getXY([].slice.call(arguments));var x=this.getX();var y=this.getY();if(pos.x!==undefined){x+=pos.x;}
if(pos.y!==undefined){y+=pos.y;}
this.setPosition(x,y);},getRotationDeg:function(){return Kinetic.Type._radToDeg(this.getRotation());},setRotationDeg:function(deg){this.setRotation(Kinetic.Type._degToRad(deg));},rotate:function(theta){this.setRotation(this.getRotation()+theta);},rotateDeg:function(deg){this.setRotation(this.getRotation()+Kinetic.Type._degToRad(deg));},moveToTop:function(){var index=this.index; this.parent.children.splice(index,1);this.parent.children.push(this);this.parent._setChildrenIndices();return true;},moveUp:function(){var index=this.index;var len=this.parent.getChildren().length;if(index<len-1){this.parent.children.splice(index,1);this.parent.children.splice(index+1,0,this);this.parent._setChildrenIndices();return true;}},moveDown:function(){var index=this.index;if(index>0){this.parent.children.splice(index,1);this.parent.children.splice(index-1,0,this);this.parent._setChildrenIndices();return true;}},moveToBottom:function(){var index=this.index;if(index>0){this.parent.children.splice(index,1);this.parent.children.unshift(this);this.parent._setChildrenIndices();return true;}},setZIndex:function(zIndex){var index=this.index;this.parent.children.splice(index,1);this.parent.children.splice(zIndex,0,this);this.parent._setChildrenIndices();},/**/
getAbsoluteOpacity:function(){var absOpacity=this.getOpacity();if(this.getParent()){absOpacity*=this.getParent().getAbsoluteOpacity();}
return absOpacity;},moveTo:function(newContainer){var parent=this.parent;parent.children.splice(this.index,1); parent._setChildrenIndices();newContainer.children.push(this);this.index=newContainer.children.length-1;this.parent=newContainer;newContainer._setChildrenIndices();},toObject:function(){var type=Kinetic.Type,obj={},attrs=this.attrs;obj.attrs={};for(var key in attrs){var val=attrs[key];if(!type._isFunction(val)&&!type._isElement(val)&&!(type._isObject(val)&&type._hasMethods(val))){obj.attrs[key]=val;}}
obj.nodeType=this.nodeType;obj.shapeType=this.shapeType;return obj;},toJSON:function(){return JSON.stringify(this.toObject());},getParent:function(){return this.parent;},getLayer:function(){return this.getParent().getLayer();},getStage:function(){if(this.getParent()){return this.getParent().getStage();}
else{return undefined;}},simulate:function(eventType,evt){this._handleEvent(eventType,evt||{});},fire:function(eventType,obj){this._executeHandlers(eventType,obj||{});},getAbsoluteTransform:function(){var am=new Kinetic.Transform();var family=[];var parent=this.parent;family.unshift(this);while(parent){family.unshift(parent);parent=parent.parent;}
var len=family.length;for(var n=0;n<len;n++){var node=family[n];var m=node.getTransform();am.multiply(m);}
return am;},getTransform:function(){var m=new Kinetic.Transform(),attrs=this.attrs,x=attrs.x,y=attrs.y,rotation=attrs.rotation,scale=attrs.scale,scaleX =scale.x,scaleY=scale.y,offset=attrs.offset,offsetX=offset.x,offsetY=offset.y;if(x!==0||y!==0){m.translate(x,y);}
if(rotation!==0){m.rotate(rotation);}
if(scaleX!==1||scaleY!==1){m.scale(scaleX,scaleY);}
if(offsetX!==0||offsetY!==0){m.translate(-1*offsetX,-1*offsetY);}
return m;},clone:function(obj){var classType=this.shapeType||this.nodeType;var node=new Kinetic[classType](this.attrs);for(var key in this.eventListeners){var allListeners=this.eventListeners[key];var len=allListeners.length;for(var n=0;n<len;n++){var listener=allListeners[n];if(listener.name.indexOf('kinetic')<0){if(!node.eventListeners[key]){node.eventListeners[key]=[];}
node.eventListeners[key].push(listener);}}}
node.setAttrs(obj);return node;},/**/
toDataURL:function(config){config=config||{};var mimeType=config.mimeType||null,quality=config.quality||null,canvas,context,x=config.x||0,y=config.y||0;if(config.width&&config.height){canvas=new Kinetic.SceneCanvas(config.width,config.height);}
else{canvas=this.getStage().bufferCanvas;canvas.clear();}
context=canvas.getContext();context.save();if(x||y){context.translate(-1*x,-1*y);}
this.drawScene(canvas);context.restore();return canvas.toDataURL(mimeType,quality);},/**/
toImage:function(config){Kinetic.Type._getImage(this.toDataURL(config),function(img){config.callback(img);});},setOffset:function(){var pos=Kinetic.Type._getXY([].slice.call(arguments));if(pos.x===undefined){pos.x=this.getOffset().x;}
if(pos.y===undefined){pos.y=this.getOffset().y;}
this.setAttr('offset',pos);},setScale:function(){var pos=Kinetic.Type._getXY([].slice.call(arguments));if(pos.x===undefined){pos.x=this.getScale().x;}
if(pos.y===undefined){pos.y=this.getScale().y;}
this.setAttr('scale',pos);},setSize:function(){var size=Kinetic.Type._getSize(Array.prototype.slice.call(arguments));this.setWidth(size.width);this.setHeight(size.height);}, getSize:function(){return{width:this.getWidth(),height:this.getHeight()};},getWidth:function(){return this.attrs.width||0;},getHeight:function(){return this.attrs.height||0;},_get:function(selector){return this.nodeType===selector?[this]:[];},_off:function(type,name){for(var i=0;i<this.eventListeners[type].length;i++){if(this.eventListeners[type][i].name===name){this.eventListeners[type].splice(i,1);if(this.eventListeners[type].length===0){delete this.eventListeners[type];break;}
i--;}}},_clearTransform:function(){var attrs=this.attrs,scale=attrs.scale,offset=attrs.offset;var trans={x:attrs.x,y:attrs.y,rotation:attrs.rotation,scale:{x:scale.x,y:scale.y},offset:{x:offset.x,y:offset.y}};this.attrs.x=0;this.attrs.y=0;this.attrs.rotation=0;this.attrs.scale={x:1,y:1};this.attrs.offset={x:0,y:0};return trans;},_setTransform:function(trans){ for(var key in trans){this.attrs[key]=trans[key];}},_fireBeforeChangeEvent:function(attr,oldVal,newVal){this._handleEvent('before'+attr.toUpperCase()+'Change',{oldVal:oldVal,newVal:newVal});},_fireChangeEvent:function(attr,oldVal,newVal){this._handleEvent(attr+'Change',{oldVal:oldVal,newVal:newVal});},setAttr:function(key,val){if(val!==undefined){var oldVal=this.attrs[key];this._fireBeforeChangeEvent(key,oldVal,val);this.attrs[key]=val;this._fireChangeEvent(key,oldVal,val);}},_handleEvent:function(eventType,evt,compareShape){if(evt&&this.nodeType==='Shape'){evt.shape=this;}
var stage=this.getStage();var el=this.eventListeners;var okayToRun=true;if(eventType==='mouseenter'&&compareShape&&this._id===compareShape._id){okayToRun=false;}
else if(eventType==='mouseleave'&&compareShape&&this._id===compareShape._id){okayToRun=false;}
if(okayToRun){if(el[eventType]){this.fire(eventType,evt);}
if(evt&&!evt.cancelBubble&&this.parent){if(compareShape&&compareShape.parent){this._handleEvent.call(this.parent,eventType,evt,compareShape.parent);}
else{this._handleEvent.call(this.parent,eventType,evt);}}}},_executeHandlers:function(eventType,evt){var events=this.eventListeners[eventType];var len=events.length;for(var i=0;i<len;i++){events[i].handler.apply(this,[evt]);}}};Kinetic.Node.addSetters=function(constructor,arr){var len=arr.length;for(var n=0;n<len;n++){var attr=arr[n];this._addSetter(constructor,attr);}};Kinetic.Node.addGetters=function(constructor,arr){var len=arr.length;for(var n=0;n<len;n++){var attr=arr[n];this._addGetter(constructor,attr);}};Kinetic.Node.addGettersSetters=function(constructor,arr){this.addSetters(constructor,arr);this.addGetters(constructor,arr);};Kinetic.Node._addSetter=function(constructor,attr){var that=this;var method='set'+attr.charAt(0).toUpperCase()+attr.slice(1);constructor.prototype[method]=function(val){this.setAttr(attr,val);};};Kinetic.Node._addGetter=function(constructor,attr){var that=this;var method='get'+attr.charAt(0).toUpperCase()+attr.slice(1);constructor.prototype[method]=function(arg){return this.attrs[attr];};};Kinetic.Node.create=function(json,container){return this._createNode(JSON.parse(json),container);};Kinetic.Node._createNode=function(obj,container){var type;if(obj.nodeType==='Shape'){if(obj.shapeType===undefined){type='Shape';}
else{type=obj.shapeType;}}
else{type=obj.nodeType;}//
if(container){ obj.attrs.container=container;}
var no=new Kinetic[type](obj.attrs);if(obj.children){var len=obj.children.length;for(var n=0;n<len;n++){no.add(this._createNode(obj.children[n]));}}
return no;};Kinetic.Node.addGettersSetters(Kinetic.Node,['x','y','rotation','opacity','name','id']);Kinetic.Node.addGetters(Kinetic.Node,['scale','offset']);Kinetic.Node.addSetters(Kinetic.Node,['width','height','listening','visible']);Kinetic.Node.prototype.isListening=Kinetic.Node.prototype.getListening;Kinetic.Node.prototype.isVisible=Kinetic.Node.prototype.getVisible;var collectionMappings=['on','off'];for(var n=0;n<2;n++){(function(i){var method=collectionMappings[i];Kinetic.Collection.prototype[method]=function(){var args=[].slice.call(arguments);args.unshift(method);this.apply.apply(this,args);};})(n);}
/**/
})();(function(){Kinetic.DD={anim:new Kinetic.Animation(),moving:false,offset:{x:0,y:0}};Kinetic.DD._startDrag=function(evt){var dd=Kinetic.DD;var node =dd.node;if(node){var pos=node.getStage().getUserPosition();var dbf=node.attrs.dragBoundFunc;var newNodePos={x:pos.x-dd.offset.x,y:pos.y-dd.offset.y};if(dbf!==undefined){newNodePos=dbf.call(node,newNodePos,evt);}
node.setAbsolutePosition(newNodePos);if(!dd.moving){dd.moving=true;node.setListening(false);node._handleEvent('dragstart',evt);}
node._handleEvent('dragmove',evt);}};Kinetic.DD._endDrag=function(evt){var dd=Kinetic.DD;var node=dd.node;if(node){node.setListening(true);if(node.nodeType==='Stage'){node.draw();}
else{node.getLayer().draw();}
if(dd.moving){dd.moving=false;node._handleEvent('dragend',evt);}}
dd.node=null;dd.anim.stop();};Kinetic.Node.prototype.setDraggable=function(draggable){this.setAttr('draggable',draggable);this._dragChange();};Kinetic.Node.prototype.getDraggable=function(){return this.attrs.draggable;};Kinetic.Node.prototype.isDragging=function(){var dd=Kinetic.DD;return dd.node&&dd.node._id===this._id&&dd.moving;};Kinetic.Node.prototype._listenDrag=function(){this._dragCleanup();var that=this;this.on('mousedown.kinetic touchstart.kinetic',function(evt){that._initDrag();});};Kinetic.Node.prototype._initDrag=function(){var dd=Kinetic.DD;var stage=this.getStage();var pos=stage.getUserPosition();if(pos){var m=this.getTransform().getTranslation();var am=this.getAbsoluteTransform().getTranslation();var ap=this.getAbsolutePosition();dd.node=this; dd.offset.x=pos.x-ap.x;dd.offset.y=pos.y-ap.y;if(this.nodeType==='Stage'){dd.anim.node=this;}
else{dd.anim.node=this.getLayer();}
dd.anim.start();}};Kinetic.Node.prototype._dragChange=function(){if(this.attrs.draggable){this._listenDrag();}
else{this._dragCleanup();var stage=this.getStage();var dd=Kinetic.DD;if(stage&&dd.node&&dd.node._id===this._id){dd._endDrag();}}};Kinetic.Node.prototype._dragCleanup=function(){this.off('mousedown.kinetic');this.off('touchstart.kinetic');};Kinetic.Node.prototype.isDraggable=Kinetic.Node.prototype.getDraggable;Kinetic.Node.addGettersSetters(Kinetic.Node,['dragBoundFunc']);})();(function(){/**/
Kinetic.Transition=function(node,config){this.node=node;this.config=config;this.tweens=[];var that=this;function addTween(c,attrs,obj,rootObj){for(var key in c){if(key!=='duration'&&key!=='easing'&&key!=='callback'){if(Kinetic.Type._isObject(c[key])){obj[key]={};addTween(c[key],attrs[key],obj[key],rootObj);}
else{that._add(that._getTween(attrs,key,c[key],obj,rootObj));}}}}
var obj={};addTween(config,node.attrs,obj,obj);var finishedTweens=0;for(var n=0;n<this.tweens.length;n++){var tween=this.tweens[n];tween.onFinished=function(){finishedTweens++;if(finishedTweens>=that.tweens.length){that.onFinished();}};}};Kinetic.Transition.prototype={start:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].start();}},stop:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].stop();}},resume:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].resume();}},_onEnterFrame:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].onEnterFrame();}},_add:function(tween){this.tweens.push(tween);},_getTween:function(attrs,prop,val,obj,rootObj){var config=this.config;var node=this.node;var easing=config.easing;if(easing===undefined){easing='linear';}
var tween=new Kinetic.Tween(node,function(i){obj[prop]=i;node.setAttrs(rootObj);},Kinetic.Tweens[easing],attrs[prop],val,config.duration);return tween;}};Kinetic.Node.prototype.transitionTo=function(config){if(!this.transAnim){this.transAnim=new Kinetic.Animation();}

var node=this.nodeType==='Stage'?this:this.getLayer();var that=this;var trans=new Kinetic.Transition(this,config);this.transAnim.func=function(){trans._onEnterFrame();};this.transAnim.node=node;trans.onFinished=function(){that.transAnim.stop();if(config.callback){config.callback();}};trans.start();this.transAnim.start();return trans;};})();(function(){/**/
Kinetic.Container=function(config){this._containerInit(config);};Kinetic.Container.prototype={_containerInit:function(config){this.children=[];Kinetic.Node.call(this,config);},getChildren:function(){return this.children;},removeChildren:function(){while(this.children.length>0){this.children[0].remove();}},add:function(child){var go=Kinetic.Global,children=this.children;child._id=Kinetic.Global.idCounter++;child.index=children.length;child.parent=this;children.push(child);var stage=child.getStage();if(!stage){go._addTempNode(child);}
else{stage._addId(child);stage._addName(child);go._pullNodes(stage);}
return this;},get:function(selector){var collection=new Kinetic.Collection();if(selector.charAt(0)==='#'){var node=this._getNodeById(selector.slice(1));if(node){collection.push(node);}}
else if(selector.charAt(0)==='.'){var nodeList=this._getNodesByName(selector.slice(1));Kinetic.Collection.apply(collection,nodeList);}//
else{var retArr=[];var children=this.getChildren();var len=children.length;for(var n=0;n<len;n++){retArr=retArr.concat(children[n]._get(selector));}
Kinetic.Collection.apply(collection,retArr);}
return collection;},_getNodeById:function(key){var stage=this.getStage();if(stage.ids[key]!==undefined&&this.isAncestorOf(stage.ids[key])){return stage.ids[key];}
return null;},_getNodesByName:function(key){var arr=this.getStage().names[key]||[];return this._getDescendants(arr);},_get:function(selector){var retArr=Kinetic.Node.prototype._get.call(this,selector);var children=this.getChildren();var len=children.length;for(var n=0;n<len;n++){retArr=retArr.concat(children[n]._get(selector));}
return retArr;},toObject:function(){var obj=Kinetic.Node.prototype.toObject.call(this);obj.children=[];var children=this.getChildren();var len=children.length;for(var n=0;n<len;n++){var child=children[n];obj.children.push(child.toObject());}
return obj;},_getDescendants:function(arr){var retArr=[];var len=arr.length;for(var n=0;n<len;n++){var node=arr[n];if(this.isAncestorOf(node)){retArr.push(node);}}
return retArr;},/**/
isAncestorOf:function(node){var parent=node.getParent();while(parent){if(parent._id===this._id){return true;}
parent=parent.getParent();}
return false;},clone:function(obj){var node =Kinetic.Node.prototype.clone.call(this,obj)
for(var key in this.children){node.add(this.children[key].clone());}
return node;},getIntersections:function(){var pos=Kinetic.Type._getXY(Array.prototype.slice.call(arguments));var arr=[];var shapes=this.get('Shape');var len=shapes.length;for(var n=0;n<len;n++){var shape=shapes[n];if(shape.isVisible()&&shape.intersects(pos)){arr.push(shape);}}
return arr;},_setChildrenIndices:function(){var children=this.children,len=children.length;for(var n=0;n<len;n++){children[n].index=n;}},draw:function(){this.drawScene();this.drawHit();},drawScene:function(canvas){if(this.isVisible()){var children=this.children,len=children.length;for(var n=0;n<len;n++){children[n].drawScene(canvas);}}},drawHit:function(){if(this.isVisible()&&this.isListening()){var children=this.children,len=children.length;for(var n=0;n<len;n++){children[n].drawHit();}}}};Kinetic.Global.extend(Kinetic.Container,Kinetic.Node);})();(function(){Kinetic.Stage=function(config){this._initStage(config);};Kinetic.Stage.prototype={_initStage:function(config){this.setDefaultAttrs({width:400,height:200});Kinetic.Container.call(this,config);this._setStageDefaultProperties();this._id=Kinetic.Global.idCounter++;this._buildDOM();this._bindContentEvents();var go=Kinetic.Global;go.stages.push(this);this._addId(this);this._addName(this);},/**/
setContainer:function(container){if(typeof container==='string'){container=document.getElementById(container);}
this.setAttr('container',container);},setHeight:function(height){Kinetic.Node.prototype.setHeight.call(this,height);this._resizeDOM();},setWidth:function(width){Kinetic.Node.prototype.setWidth.call(this,width);this._resizeDOM();},clear:function(){var layers=this.children;for(var n=0;n<layers.length;n++){layers[n].clear();}},reset:function(){this.removeChildren(); this._setStageDefaultProperties();this.setAttrs(this.defaultNodeAttrs);},getMousePosition:function(){return this.mousePos;},getTouchPosition:function(){return this.touchPos;},/**/
getUserPosition:function(){return this.getTouchPosition()||this.getMousePosition();},getStage:function(){return this;},getDOM:function(){return this.content;},toDataURL:function(config){config=config||{};var mimeType=config.mimeType||null,quality=config.quality||null,x=config.x||0,y=config.y||0,canvas=new Kinetic.SceneCanvas(config.width||this.getWidth(),config.height||this.getHeight()),context=canvas.getContext(),layers=this.children;if(x||y){context.translate(-1*x,-1*y);}
function drawLayer(n){var layer=layers[n];var layerUrl=layer.toDataURL();var imageObj=new Image();imageObj.onload=function(){context.drawImage(imageObj,0,0);if(n<layers.length-1){drawLayer(n+1);}
else{config.callback(canvas.toDataURL(mimeType,quality));}};imageObj.src=layerUrl;}
drawLayer(0);},toImage:function(config){var cb=config.callback;config.callback=function(dataUrl){Kinetic.Type._getImage(dataUrl,function(img){cb(img);});};this.toDataURL(config);},getIntersection:function(pos){var shape;var layers=this.getChildren();for(var n=layers.length-1;n>=0;n--){var layer=layers[n];if(layer.isVisible()&&layer.isListening()){var p=layer.hitCanvas.context.getImageData(Math.round(pos.x),Math.round(pos.y),1,1).data;if(p[3]===255){var colorKey=Kinetic.Type._rgbToHex(p[0],p[1],p[2]);shape=Kinetic.Global.shapes[colorKey];return{shape:shape,pixel:p};}
else if(p[0]>0||p[1]>0||p[2]>0||p[3]>0){return{pixel:p};}}}
return null;},_getNodeById:function(key){return this.ids[key]||null;},_getNodesByName:function(key){return this.names[key]||[];},_resizeDOM:function(){if(this.content){var width=this.attrs.width;var height=this.attrs.height;this.content.style.width=width+'px';this.content.style.height=height+'px';this.bufferCanvas.setSize(width,height);this.hitCanvas.setSize(width,height);var layers=this.children;for(var n=0;n<layers.length;n++){var layer=layers[n];layer.getCanvas().setSize(width,height);layer.hitCanvas.setSize(width,height);layer.draw();}}},add:function(layer){Kinetic.Container.prototype.add.call(this,layer);layer.canvas.setSize(this.attrs.width,this.attrs.height);layer.hitCanvas.setSize(this.attrs.width,this.attrs.height);layer.draw();this.content.appendChild(layer.canvas.element);return this;},_setUserPosition:function(evt){if(!evt){evt=window.event;}
this._setMousePosition(evt);this._setTouchPosition(evt);},_bindContentEvents:function(){var go=Kinetic.Global;var that=this;var events=['mousedown','mousemove','mouseup','mouseout','touchstart','touchmove','touchend'];for(var n=0;n<events.length;n++){var pubEvent=events[n];(function(){var event=pubEvent;that.content.addEventListener(event,function(evt){that['_'+event](evt);},false);}());}},_mouseout:function(evt){this._setUserPosition(evt);var dd=Kinetic.DD;var targetShape=this.targetShape;if(targetShape&&(!dd||!dd.moving)){targetShape._handleEvent('mouseout',evt);targetShape._handleEvent('mouseleave',evt);this.targetShape=null;}
this.mousePos=undefined;if(dd){dd._endDrag(evt);}},_mousemove:function(evt){this._setUserPosition(evt);var dd=Kinetic.DD;var obj=this.getIntersection(this.getUserPosition());if(obj){var shape=obj.shape;if(shape){if((!dd||!dd.moving)&&obj.pixel[3]===255&&(!this.targetShape||this.targetShape._id!==shape._id)){if(this.targetShape){this.targetShape._handleEvent('mouseout',evt,shape);this.targetShape._handleEvent('mouseleave',evt,shape);}
shape._handleEvent('mouseover',evt,this.targetShape);shape._handleEvent('mouseenter',evt,this.targetShape);this.targetShape=shape;}
else{shape._handleEvent('mousemove',evt);}}}
else if(this.targetShape&&(!dd||!dd.moving)){this.targetShape._handleEvent('mouseout',evt);this.targetShape._handleEvent('mouseleave',evt);this.targetShape=null;}
if(dd){dd._startDrag(evt);}},_mousedown:function(evt){this._setUserPosition(evt);var obj=this.getIntersection(this.getUserPosition());if(obj&&obj.shape){var shape=obj.shape;this.clickStart=true;shape._handleEvent('mousedown',evt);}
if(Kinetic.DD&&this.attrs.draggable){this._initDrag();}},_mouseup:function(evt){this._setUserPosition(evt);var dd=Kinetic.DD;var obj=this.getIntersection(this.getUserPosition());var that=this;if(obj&&obj.shape){var shape=obj.shape;shape._handleEvent('mouseup',evt);
if(this.clickStart){if(!dd||!dd.moving||!dd.node){shape._handleEvent('click',evt);if(this.inDoubleClickWindow){shape._handleEvent('dblclick',evt);}
this.inDoubleClickWindow=true;setTimeout(function(){that.inDoubleClickWindow=false;},this.dblClickWindow);}}}
this.clickStart=false;if(dd){dd._endDrag(evt);}},_touchstart:function(evt){this._setUserPosition(evt);evt.preventDefault();var obj=this.getIntersection(this.getUserPosition());if(obj&&obj.shape){var shape=obj.shape;this.tapStart=true;shape._handleEvent('touchstart',evt);}
if(Kinetic.DD&&this.attrs.draggable){this._initDrag();}},_touchend:function(evt){this._setUserPosition(evt);var dd=Kinetic.DD;var obj=this.getIntersection(this.getUserPosition());var that=this;if(obj&&obj.shape){var shape=obj.shape;shape._handleEvent('touchend',evt);if(this.tapStart){/**/
if(!dd||!dd.moving||!dd.node){shape._handleEvent('tap',evt);if(this.inDoubleClickWindow){shape._handleEvent('dbltap',evt);}
this.inDoubleClickWindow=true;setTimeout(function(){that.inDoubleClickWindow=false;},this.dblClickWindow);}}}
this.tapStart=false;if(dd){dd._endDrag(evt);}}, _touchmove:function(evt){this._setUserPosition(evt);var dd=Kinetic.DD;evt.preventDefault();var obj=this.getIntersection(this.getUserPosition());if(obj&&obj.shape){var shape=obj.shape;shape._handleEvent('touchmove',evt);}
if(dd){dd._startDrag(evt);}},_setMousePosition:function(evt){var mouseX=evt.clientX-this._getContentPosition().left;var mouseY=evt.clientY-this._getContentPosition().top;this.mousePos={x:mouseX,y:mouseY};},_setTouchPosition:function(evt){if(evt.touches!==undefined&&evt.touches.length===1){var touch=evt.touches[0];var touchX=touch.clientX-this._getContentPosition().left;var touchY=touch.clientY-this._getContentPosition().top;this.touchPos={x:touchX,y:touchY};}},_getContentPosition:function(){var rect=this.content.getBoundingClientRect();return{top:rect.top,left:rect.left};},_buildDOM:function(){this.content=document.createElement('div');this.content.style.position='relative'; this.content.style.display='inline-block';this.content.className='kineticjs-content';this.attrs.container.appendChild(this.content);this.bufferCanvas=new Kinetic.SceneCanvas();this.hitCanvas=new Kinetic.HitCanvas(0,0);this._resizeDOM();},_addId:function(node){if(node.attrs.id!==undefined){this.ids[node.attrs.id]=node;}},_removeId:function(id){if(id!==undefined){delete this.ids[id];}},_addName:function(node){var name=node.attrs.name;if(name!==undefined){if(this.names[name]===undefined){this.names[name]=[];}
this.names[name].push(node);}},_removeName:function(name,_id){if(name!==undefined){var nodes=this.names[name];if(nodes!==undefined){for(var n=0;n<nodes.length;n++){var no=nodes[n];if(no._id===_id){nodes.splice(n,1);}}
if(nodes.length===0){delete this.names[name];}}}},_onContent:function(typesStr,handler){var types=typesStr.split(' ');for(var n=0;n<types.length;n++){var baseEvent=types[n];this.content.addEventListener(baseEvent,handler,false);}},_setStageDefaultProperties:function(){this.nodeType='Stage';this.dblClickWindow=400;this.targetShape=null;this.mousePos=undefined;this.clickStart=false;this.touchPos=undefined;this.tapStart=false;this.ids={};this.names={};}};Kinetic.Global.extend(Kinetic.Stage,Kinetic.Container);Kinetic.Node.addGetters(Kinetic.Stage,['container']);})();(function(){/**/
Kinetic.Layer=function(config){this._initLayer(config);};Kinetic.Layer.prototype={_initLayer:function(config){this.setDefaultAttrs({clearBeforeDraw:true});this.nodeType='Layer';this.beforeDrawFunc=undefined;this.afterDrawFunc=undefined;this.canvas=new Kinetic.SceneCanvas();this.canvas.getElement().style.position='absolute';this.hitCanvas=new Kinetic.HitCanvas(0,0);Kinetic.Container.call(this,config);},draw:function(){if(this.beforeDrawFunc!==undefined){this.beforeDrawFunc.call(this);}
Kinetic.Container.prototype.draw.call(this);if(this.afterDrawFunc!==undefined){this.afterDrawFunc.call(this);}},drawHit:function(){this.hitCanvas.clear();Kinetic.Container.prototype.drawHit.call(this);},drawScene:function(canvas){ canvas=canvas||this.getCanvas();if(this.attrs.clearBeforeDraw){ canvas.clear();}
Kinetic.Container.prototype.drawScene.call(this,canvas);},beforeDraw:function(func){this.beforeDrawFunc=func;},afterDraw:function(func){this.afterDrawFunc=func;},getCanvas:function(){return this.canvas;},getContext:function(){return this.canvas.context;},clear:function(){this.getCanvas().clear();},setVisible:function(visible){Kinetic.Node.prototype.setVisible.call(this,visible);if(visible){this.canvas.element.style.display='block';this.hitCanvas.element.style.display='block';}
else{this.canvas.element.style.display='none';this.hitCanvas.element.style.display='none';}},setZIndex:function(index){Kinetic.Node.prototype.setZIndex.call(this,index);var stage=this.getStage();if(stage){stage.content.removeChild(this.canvas.element);if(index<stage.getChildren().length-1){stage.content.insertBefore(this.canvas.element,stage.getChildren()[index+1].canvas.element);}
else{stage.content.appendChild(this.canvas.element);}}},moveToTop:function(){Kinetic.Node.prototype.moveToTop.call(this);var stage=this.getStage();if(stage){stage.content.removeChild(this.canvas.element);stage.content.appendChild(this.canvas.element);}},moveUp:function(){if(Kinetic.Node.prototype.moveUp.call(this)){var stage=this.getStage();if(stage){stage.content.removeChild(this.canvas.element);if(this.index<stage.getChildren().length-1){stage.content.insertBefore(this.canvas.element,stage.getChildren()[this.index+1].canvas.element);}
else{stage.content.appendChild(this.canvas.element);}}}},moveDown:function(){if(Kinetic.Node.prototype.moveDown.call(this)){var stage=this.getStage();if(stage){var children=stage.getChildren();stage.content.removeChild(this.canvas.element);stage.content.insertBefore(this.canvas.element,children[this.index+1].canvas.element);}}},moveToBottom:function(){if(Kinetic.Node.prototype.moveToBottom.call(this)){var stage=this.getStage();if(stage){var children=stage.getChildren();stage.content.removeChild(this.canvas.element);stage.content.insertBefore(this.canvas.element,children[1].canvas.element);}}},getLayer:function(){return this;},remove:function(){var stage=this.getStage();Kinetic.Node.prototype.remove.call(this);try{stage.content.removeChild(this.canvas.element);}
catch(e){Kinetic.Global.warn('unable to remove layer scene canvas element from the document');}}};Kinetic.Global.extend(Kinetic.Layer,Kinetic.Container);Kinetic.Node.addGettersSetters(Kinetic.Layer,['clearBeforeDraw']);})();(function(){/**/
Kinetic.Group=function(config){this._initGroup(config);};Kinetic.Group.prototype={_initGroup:function(config){this.nodeType='Group';Kinetic.Container.call(this,config);}};Kinetic.Global.extend(Kinetic.Group,Kinetic.Container);})();(function(){/**/
Kinetic.Shape=function(config){this._initShape(config);};Kinetic.Shape.prototype={_initShape:function(config){this.nodeType='Shape';var shapes=Kinetic.Global.shapes;var key;while(true){key=Kinetic.Type._getRandomColorKey();if(key&&!(key in shapes)){break;}}
this.colorKey=key;shapes[key]=this;Kinetic.Node.call(this,config);},getContext:function(){return this.getLayer().getContext();},getCanvas:function(){return this.getLayer().getCanvas();},_getFillType:function(fill){var type=Kinetic.Type;if(!fill){return undefined;}
else if(type._isString(fill)){return 'COLOR';}
else if(fill.image){return 'PATTERN';}
else if(fill.start&&fill.end&&!fill.start.radius&&!fill.end.radius){return 'LINEAR_GRADIENT';}
else if(fill.start&&fill.end&&type._isNumber(fill.start.radius)&&type._isNumber(fill.end.radius)){return 'RADIAL_GRADIENT';}
else{return 'UNKNOWN';}},setShadow:function(config){var type=Kinetic.Type;if(config.offset!==undefined){config.offset=type._getXY(config.offset);}
this.setAttr('shadow',type._merge(config,this.getShadow()));},setFill:function(fill){var type=Kinetic.Type;var oldFill=this.getFill();var fillType=this._getFillType(fill);var oldFillType=this._getFillType(oldFill);var newOrOldFillIsColor=fillType==='COLOR'||oldFillType==='COLOR';var changedFillType=fillType===oldFillType||fillType==='UNKNOWN';if(fill.offset!==undefined){fill.offset=type._getXY(fill.offset);}
if(fill.scale!==undefined){fill.scale=type._getXY(fill.scale);}
if(fill.rotationDeg!==undefined){fill.rotation=type._degToRad(fill.rotationDeg);}
/**/
if(!newOrOldFillIsColor&&changedFillType){fill=type._merge(fill,oldFill);}
this.setAttr('fill',fill);},setSize:function(){var size=Kinetic.Type._getSize(Array.prototype.slice.call(arguments));this.setWidth(size.width);this.setHeight(size.height);},getSize:function(){return{width:this.getWidth(),height:this.getHeight()};},_get:function(selector){return this.nodeType===selector||this.shapeType===selector?[this]:[];},intersects:function(){var pos=Kinetic.Type._getXY(Array.prototype.slice.call(arguments));var stage=this.getStage();var hitCanvas=stage.hitCanvas;hitCanvas.clear();this.drawScene(hitCanvas);var p=hitCanvas.context.getImageData(Math.round(pos.x),Math.round(pos.y),1,1).data;return p[3]>0;},remove:function(){Kinetic.Node.prototype.remove.call(this);delete Kinetic.Global.shapes[this.colorKey];},drawScene:function(canvas){var attrs=this.attrs,drawFunc=attrs.drawFunc,canvas=canvas||this.getLayer().getCanvas(),context=canvas.getContext();if(drawFunc&&this.isVisible()){var stage=this.getStage(),family=[],parent=this.parent;family.unshift(this);while(parent){family.unshift(parent);parent=parent.parent;}
context.save();canvas._handlePixelRatio();canvas._applyOpacity(this);canvas._applyLineJoin(this);var len=family.length;for(var n=0;n<len;n++){var node=family[n],t=node.getTransform(),m=t.getMatrix();context.transform(m[0],m[1],m[2],m[3],m[4],m[5]);}
drawFunc.call(this,canvas);context.restore();}},drawHit:function(){var attrs=this.attrs,drawFunc=attrs.drawHitFunc||attrs.drawFunc,canvas=this.getLayer().hitCanvas,context=canvas.getContext();if(drawFunc&&this.isVisible()&&this.isListening()){var stage=this.getStage(),family=[],parent=this.parent;family.unshift(this);while(parent){family.unshift(parent);parent=parent.parent;}
context.save();canvas._applyLineJoin(this);var len=family.length;for(var n=0;n<len;n++){var node=family[n],t=node.getTransform(),m=t.getMatrix();context.transform(m[0],m[1],m[2],m[3],m[4],m[5]);}
drawFunc.call(this,canvas);context.restore();}},_setDrawFuncs:function(){if(!this.attrs.drawFunc&&this.drawFunc){this.setDrawFunc(this.drawFunc);}
if(!this.attrs.drawHitFunc&&this.drawHitFunc){this.setDrawHitFunc(this.drawHitFunc);}}};Kinetic.Global.extend(Kinetic.Shape,Kinetic.Node);Kinetic.Node.addGettersSetters(Kinetic.Shape,['stroke','lineJoin','lineCap','strokeWidth','drawFunc','drawHitFunc','cornerRadius','dashArray']);Kinetic.Node.addGetters(Kinetic.Shape,['shadow','fill']);/**/
/**/
})();(function(){Kinetic.Rect=function(config){this._initRect(config);}
Kinetic.Rect.prototype={_initRect:function(config){this.setDefaultAttrs({width:0,height:0,cornerRadius:0});this.shapeType="Rect";Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var context=canvas.getContext();context.beginPath();var cornerRadius=this.getCornerRadius(),width=this.getWidth(),height=this.getHeight();if(cornerRadius===0){context.rect(0,0,width,height);}
else{context.moveTo(cornerRadius,0);context.lineTo(width-cornerRadius,0);context.arc(width-cornerRadius,cornerRadius,cornerRadius,Math.PI*3/2,0,false);
context.lineTo(width,height-cornerRadius);context.arc(width-cornerRadius,height-cornerRadius,cornerRadius,0,Math.PI/2,false);context.lineTo(cornerRadius,height);context.arc(cornerRadius,height-cornerRadius,cornerRadius,Math.PI/2,Math.PI,false);context.lineTo(0,cornerRadius);context.arc(cornerRadius,cornerRadius,cornerRadius,Math.PI,Math.PI*3/2,false);}
context.closePath();canvas.fillStroke(this);}};Kinetic.Global.extend(Kinetic.Rect,Kinetic.Shape);})();(function(){Kinetic.Circle=function(config){this._initCircle(config);};Kinetic.Circle.prototype={_initCircle:function(config){this.setDefaultAttrs({radius:0});this.shapeType='Circle';Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var context=canvas.getContext();context.beginPath();context.arc(0,0,this.getRadius(),0,Math.PI*2,true);context.closePath();canvas.fillStroke(this);},getWidth:function(){return this.getRadius()*2;},getHeight:function(){return this.getRadius()*2;},setWidth:function(width){Kinetic.Node.prototype.setWidth.call(this,width);this.setRadius(width/2);},setHeight:function(height){Kinetic.Node.prototype.setHeight.call(this,height);this.setRadius(height/2);}};Kinetic.Global.extend(Kinetic.Circle,Kinetic.Shape);Kinetic.Node.addGettersSetters(Kinetic.Circle,['radius']);})();(function(){Kinetic.Wedge=function(config){this._initWedge(config);};Kinetic.Wedge.prototype={_initWedge:function(config){this.setDefaultAttrs({radius:0,angle:0,clickwise:true});this.shapeType='Wedge';Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var context=canvas.getContext();context.beginPath();context.arc(0,0,this.getRadius(),0,this.getAngle(),this.getClockwise());context.lineTo(0,0);context.closePath();canvas.fillStroke(this);},setAngleDeg:function(deg){this.setAngle(Kinetic.Type._degToRad(deg));},getAngleDeg:function(){return Kinetic.Type._radToDeg(this.getAngle());}};Kinetic.Global.extend(Kinetic.Wedge,Kinetic.Shape);Kinetic.Node.addGettersSetters(Kinetic.Wedge,['radius','angle','clockwise']);/**/
/**/})();(function(){Kinetic.Ellipse=function(config){this._initEllipse(config);};Kinetic.Ellipse.prototype={_initEllipse:function(config){this.setDefaultAttrs({radius:{x:0,y:0}});this.shapeType="Ellipse";Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var context=canvas.getContext(),r=this.getRadius();context.beginPath();context.save();if(r.x!==r.y){context.scale(1,r.y/r.x);}
context.arc(0,0,r.x,0,Math.PI*2,true);context.restore();context.closePath();canvas.fillStroke(this);},setRadius:function(){var pos=Kinetic.Type._getXY([].slice.call(arguments));this.setAttr('radius',Kinetic.Type._merge(pos,this.getRadius()));},getWidth:function(){return this.getRadius().x*2;},getHeight:function(){ return this.getRadius().y*2;},setWidth:function(width){Kinetic.Node.prototype.setWidth.call(this,width);this.setRadius({x:width/2});},setHeight:function(height){Kinetic.Node.prototype.setHeight.call(this,height);this.setRadius({y:height/2});}};Kinetic.Global.extend(Kinetic.Ellipse,Kinetic.Shape);Kinetic.Node.addGetters(Kinetic.Ellipse,['radius']);})();(function(){Kinetic.Image=function(config){this._initImage(config);};Kinetic.Image.prototype={_initImage:function(config){this.shapeType="Image";Kinetic.Shape.call(this,config);this._setDrawFuncs();var that=this;this.on('imageChange',function(evt){that._syncSize();});this._syncSize();},drawFunc:function(canvas){var width=this.getWidth(),height=this.getHeight(),params,that=this,context=canvas.getContext();context.beginPath();context.rect(0,0,width,height);context.closePath();canvas.fillStroke(this);if(this.attrs.image){if(this.attrs.crop&&this.attrs.crop.width&&this.attrs.crop.height){var cropX=this.attrs.crop.x||0; var cropY=this.attrs.crop.y||0;var cropWidth=this.attrs.crop.width;var cropHeight=this.attrs.crop.height;params=[this.attrs.image,cropX,cropY,cropWidth,cropHeight,0,0,width,height];}
else{params=[this.attrs.image,0,0,width,height];}
if(this.getShadow()){canvas.applyShadow(this,function(){that._drawImage(context,params);});}
else{this._drawImage(context,params);}}},drawHitFunc:function(canvas){var width=this.getWidth(),height=this.getHeight(),imageHitRegion=this.imageHitRegion,appliedShadow=false,context=canvas.getContext();if(imageHitRegion){context.drawImage(imageHitRegion,0,0,width,height);context.beginPath();context.rect(0,0,width,height);context.closePath();canvas.stroke(this);}
else{context.beginPath();context.rect(0,0,width,height);context.closePath();canvas.fillStroke(this);}},applyFilter:function(filter,config,callback){var canvas=new Kinetic.Canvas(this.attrs.image.width,this.attrs.image.height);var context=canvas.getContext();context.drawImage(this.attrs.image,0,0);try{var imageData=context.getImageData(0,0,canvas.getWidth(),canvas.getHeight());filter(imageData,config);var that=this;Kinetic.Type._getImage(imageData,function(imageObj){that.setImage(imageObj);if(callback){callback();}});}
catch(e){Kinetic.Global.warn('Unable to apply filter. '+e.message);}},/**/
setCrop:function(){var config=[].slice.call(arguments);var pos=Kinetic.Type._getXY(config);var size=Kinetic.Type._getSize(config);var both=Kinetic.Type._merge(pos,size);this.setAttr('crop',Kinetic.Type._merge(both,this.getCrop()));},createImageHitRegion:function(callback){var canvas=new Kinetic.Canvas(this.attrs.width,this.attrs.height);var context=canvas.getContext();context.drawImage(this.attrs.image,0,0);try{var imageData=context.getImageData(0,0,canvas.getWidth(),canvas.getHeight());var data=imageData.data;var rgbColorKey=Kinetic.Type._hexToRgb(this.colorKey);for(var i=0,n=data.length;i<n;i+=4){data[i]=rgbColorKey.r;data[i+1]=rgbColorKey.g;data[i+2]=rgbColorKey.b;}
var that=this;Kinetic.Type._getImage(imageData,function(imageObj){that.imageHitRegion=imageObj;if(callback){callback();}});}
catch(e){Kinetic.Global.warn('Unable to create image hit region. '+e.message);}},clearImageHitRegion:function(){delete this.imageHitRegion;},_syncSize:function(){if(this.attrs.image){if(!this.attrs.width){this.setWidth(this.attrs.image.width);}
if(!this.attrs.height){this.setHeight(this.attrs.image.height);}}},_drawImage:function(context,a){if(a.length===5){context.drawImage(a[0],a[1],a[2],a[3],a[4]);}
else if(a.length===9){context.drawImage(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8]);}}};Kinetic.Global.extend(Kinetic.Image,Kinetic.Shape);Kinetic.Node.addGettersSetters(Kinetic.Image,['image']);Kinetic.Node.addGetters(Kinetic.Image,['crop']);})();(function(){Kinetic.Polygon=function(config){this._initPolygon(config);};Kinetic.Polygon.prototype={_initPolygon:function(config){this.setDefaultAttrs({points:[]});this.shapeType="Polygon";Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var context=canvas.getContext(),points=this.getPoints(),length=points.length;context.beginPath();context.moveTo(points[0].x,points[0].y);for(var n=1;n<length;n++){context.lineTo(points[n].x,points[n].y);}
context.closePath();canvas.fillStroke(this);},setPoints:function(val){this.setAttr('points',Kinetic.Type._getPoints(val));}};Kinetic.Global.extend(Kinetic.Polygon,Kinetic.Shape);Kinetic.Node.addGetters(Kinetic.Polygon,['points']);})();(function(){Kinetic.Text=function(config){this._initText(config);};Kinetic.Text.prototype={_initText:function(config){this.setDefaultAttrs({fontFamily:'Calibri',text:'',fontSize:12,align:'left',verticalAlign:'top',fontStyle:'normal',padding:0,width:'auto',height:'auto',detectionType:'path',cornerRadius:0, lineHeight:1.2});this.dummyCanvas=document.createElement('canvas');this.shapeType="Text";Kinetic.Shape.call(this,config);this._setDrawFuncs();var attrs=['fontFamily','fontSize','fontStyle','padding','align','lineHeight','text','width','height'];var that=this;for(var n=0;n<attrs.length;n++){var attr=attrs[n];this.on(attr+'Change.kinetic',that._setTextData);}
that._setTextData();},drawFunc:function(canvas){ var context=canvas.getContext();Kinetic.Rect.prototype.drawFunc.call(this,canvas);var p=this.attrs.padding;var lineHeightPx=this.attrs.lineHeight*this.getTextHeight();var textArr=this.textArr;context.font=this.attrs.fontStyle+' '+this.attrs.fontSize+'pt '+this.attrs.fontFamily;context.textBaseline='middle';context.textAlign='left';context.save();context.translate(p,0);context.translate(0,p+this.getTextHeight()/2);for(var n=0;n<textArr.length;n++){var text=textArr[n];context.save();if(this.attrs.align==='right'){context.translate(this.getWidth()-this._getTextSize(text).width-p*2,0);}
else if(this.attrs.align==='center'){context.translate((this.getWidth()-this._getTextSize(text).width-p*2)/2,0);}
canvas.fillStrokeText(this,text);context.restore();context.translate(0,lineHeightPx);}
context.restore();},drawHitFunc:Kinetic.Rect.prototype.drawFunc,setText:function(text){var str=Kinetic.Type._isString(text)?text:text.toString();this.setAttr('text',str);},getWidth:function(){return this.attrs.width==='auto'?this.getTextWidth()+this.attrs.padding*2:this.attrs.width;},getHeight:function(){return this.attrs.height==='auto'?(this.getTextHeight()*this.textArr.length*this.attrs.lineHeight)+this.attrs.padding*2:this.attrs.height;},getTextWidth:function(){return this.textWidth;},getTextHeight:function(){return this.textHeight;},_getTextSize:function(text){var dummyCanvas=this.dummyCanvas;var context=dummyCanvas.getContext('2d');context.save();context.font=this.attrs.fontStyle+' '+this.attrs.fontSize+'pt '+this.attrs.fontFamily;var metrics=context.measureText(text);context.restore();return{width:metrics.width,height:parseInt(this.attrs.fontSize,10)};},setTextShadow:function(config){var type=Kinetic.Type;if(config.offset!==undefined){config.offset=type._getXY(config.offset);}
this.setAttr('textShadow',type._merge(config,this.getTextShadow()));},/***/
_setTextData:function(){var charArr=this.attrs.text.split('');var arr=[];var row=0;var addLine=true;this.textWidth=0;this.textHeight=this._getTextSize(this.attrs.text).height;var lineHeightPx=this.attrs.lineHeight*this.textHeight;while(charArr.length>0&&addLine&&(this.attrs.height==='auto'||lineHeightPx*(row+1)<this.attrs.height-this.attrs.padding*2)){var index=0;var line=undefined;addLine=false;while(index<charArr.length){if(charArr.indexOf('\n')===index){charArr.splice(index,1);line=charArr.splice(0,index).join('');break;}
var lineArr=charArr.slice(0,index);if(this.attrs.width!=='auto'&&this._getTextSize(lineArr.join('')).width>this.attrs.width-this.attrs.padding*2){if(index==0){break;}
var lastSpace=lineArr.lastIndexOf(' ');var lastDash=lineArr.lastIndexOf('-');var wrapIndex=Math.max(lastSpace,lastDash);if(wrapIndex>=0){line=charArr.splice(0,1+wrapIndex).join('');break;}
/**/
line=charArr.splice(0,index).join('');break;}
index++;if(index===charArr.length){line=charArr.splice(0,index).join('');}}
this.textWidth=Math.max(this.textWidth,this._getTextSize(line).width);if(line!==undefined){arr.push(line);addLine=true;}
row++;}
this.textArr=arr;}};Kinetic.Global.extend(Kinetic.Text,Kinetic.Shape);var fillText=function(shape,text,skipShadow){var textFill=shape.getTextFill(),textShadow=shape.getTextShadow(),context=this.context;if(textFill){context.save();if(!skipShadow&&textShadow){this._applyTextShadow(shape);}
context.fillStyle=textFill;context.fillText(text,0,0);context.restore();if(!skipShadow&&textShadow&&textShadow.opacity){this.fillText(shape,text,true);}}};var strokeText=function(shape,text,skipShadow){var textStroke=shape.getTextStroke(),textStrokeWidth=shape.getTextStrokeWidth(),textShadow=shape.getTextShadow(),context=this.context;if(textStroke||textStrokeWidth){context.save();if(!skipShadow&&textShadow){this._applyTextShadow(shape);}
context.lineWidth=textStrokeWidth||2;context.strokeStyle=textStroke||'black'; context.strokeText(text,0,0);context.restore();if(!skipShadow&&textShadow&&textShadow.opacity){this.strokeText(shape,text,true);}}};var fillStrokeText=function(shape,text){this.fillText(shape,text);this.strokeText(shape,text,shape.getTextShadow()&&shape.getTextFill());};var _applyTextShadow=function(shape){var textShadow=shape.getTextShadow(),context=this.context;if(textShadow){var aa=shape.getAbsoluteOpacity();var color=textShadow.color||'black';var blur=textShadow.blur||5;var offset=textShadow.offset||{x:0,y:0};if(textShadow.opacity){context.globalAlpha=textShadow.opacity*aa;}
context.shadowColor=color;context.shadowBlur=blur;context.shadowOffsetX=offset.x;context.shadowOffsetY=offset.y;}};Kinetic.SceneCanvas.prototype.fillText=fillText;Kinetic.SceneCanvas.prototype.strokeText=strokeText;Kinetic.SceneCanvas.prototype.fillStrokeText=fillStrokeText;Kinetic.SceneCanvas.prototype._applyTextShadow=_applyTextShadow;Kinetic.HitCanvas.prototype.fillText=fillText;Kinetic.HitCanvas.prototype.strokeText=strokeText;Kinetic.HitCanvas.prototype.fillStrokeText=fillStrokeText;Kinetic.HitCanvas.prototype._applyTextShadow=_applyTextShadow;Kinetic.Node.addGettersSetters(Kinetic.Text,['fontFamily','fontSize','fontStyle','textFill','textStroke','textStrokeWidth','padding','align','lineHeight']);Kinetic.Node.addGetters(Kinetic.Text,['text','textShadow']);/**/
/**/
})();(function(){Kinetic.Line=function(config){this._initLine(config);};Kinetic.Line.prototype={_initLine:function(config){this.setDefaultAttrs({points:[],lineCap:'butt',dashArray:[],detectionType:'pixel'});this.shapeType="Line";Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var lastPos={},points=this.getPoints(),length=points.length,dashArray=this.getDashArray(),dashLength=dashArray.length,context=canvas.getContext();context.beginPath();context.moveTo(points[0].x,points[0].y);for(var n=1;n<length;n++){var point=points[n];context.lineTo(point.x,point.y);}
canvas.stroke(this);},setPoints:function(val){this.setAttr('points',Kinetic.Type._getPoints(val));}};Kinetic.Global.extend(Kinetic.Line,Kinetic.Shape);//
Kinetic.Node.addGetters(Kinetic.Line,['points']);})();(function(){Kinetic.Sprite=function(config){this._initSprite(config);};Kinetic.Sprite.prototype={_initSprite:function(config){this.setDefaultAttrs({index:0,frameRate:17});this.shapeType="Sprite";Kinetic.Shape.call(this,config);this._setDrawFuncs();this.anim=new Kinetic.Animation();var that=this;this.on('animationChange',function(){that.setIndex(0);});},drawFunc:function(canvas){var anim=this.attrs.animation,index=this.attrs.index,f=this.attrs.animations[anim][index],context=canvas.getContext(),image=this.attrs.image;if(image){context.drawImage(image,f.x,f.y,f.width,f.height,0,0,f.width,f.height);}},drawHitFunc:function(canvas){var anim=this.attrs.animation,index=this.attrs.index,f=this.attrs.animations[anim][index],context=canvas.getContext();context.beginPath();context.rect(0,0,f.width,f.height);context.closePath();canvas.fill(this);},start:function(){var that=this;var layer=this.getLayer();this.anim.node=layer;this.interval=setInterval(function(){var index=that.attrs.index;that._updateIndex();if(that.afterFrameFunc&&index===that.afterFrameIndex){that.afterFrameFunc();delete that.afterFrameFunc;delete that.afterFrameIndex;}},1000/this.attrs.frameRate);this.anim.start();},/**/
stop:function(){this.anim.stop();clearInterval(this.interval);},afterFrame:function(index,func){this.afterFrameIndex=index;this.afterFrameFunc=func;},_updateIndex:function(){var i=this.attrs.index;var a=this.attrs.animation;if(i<this.attrs.animations[a].length-1){this.attrs.index++;}
else{this.attrs.index=0;}}};Kinetic.Global.extend(Kinetic.Sprite,Kinetic.Shape);Kinetic.Node.addGettersSetters(Kinetic.Sprite,['animation','animations','index']);})();(function(){/**/
Kinetic.Star=function(config){this._initStar(config);};Kinetic.Star.prototype={_initStar:function(config){this.setDefaultAttrs({numPoints:0,innerRadius:0,outerRadius:0});this.shapeType="Star";Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var context=canvas.getContext(),innerRadius=this.attrs.innerRadius,outerRadius=this.attrs.outerRadius,numPoints=this.attrs.numPoints;context.beginPath();context.moveTo(0,0-this.attrs.outerRadius);for(var n=1;n<numPoints*2;n++){var radius=n%2===0?outerRadius:innerRadius;var x=radius*Math.sin(n*Math.PI/numPoints);var y=-1*radius*Math.cos(n*Math.PI/numPoints);context.lineTo(x,y);}
context.closePath();canvas.fillStroke(this);}};Kinetic.Global.extend(Kinetic.Star,Kinetic.Shape);Kinetic.Node.addGettersSetters(Kinetic.Star,['numPoints','innerRadius','outerRadius']);/**/
})();(function(){Kinetic.RegularPolygon=function(config){this._initRegularPolygon(config);};Kinetic.RegularPolygon.prototype={_initRegularPolygon:function(config){this.setDefaultAttrs({radius:0,sides:0});this.shapeType="RegularPolygon";//
Kinetic.Shape.call(this,config);this._setDrawFuncs();},drawFunc:function(canvas){var context=canvas.getContext(),sides=this.attrs.sides,radius=this.attrs.radius;context.beginPath();context.moveTo(0,0-radius);for(var n=1;n<sides;n++){var x=radius*Math.sin(n*2*Math.PI/sides);var y=-1*radius*Math.cos(n*2*Math.PI/sides);context.lineTo(x,y);}
context.closePath();canvas.fillStroke(this);}};Kinetic.Global.extend(Kinetic.RegularPolygon,Kinetic.Shape);Kinetic.Node.addGettersSetters(Kinetic.RegularPolygon,['radius','sides']);})();(function(){Kinetic.Path=function(config){this._initPath(config);};Kinetic.Path.prototype={_initPath:function(config){this.shapeType="Path";this.dataArray=[];var that=this;Kinetic.Shape.call(this,config);this._setDrawFuncs();this.dataArray=Kinetic.Path.parsePathData(this.attrs.data);this.on('dataChange',function(){that.dataArray=Kinetic.Path.parsePathData(that.attrs.data);});},drawFunc:function(canvas){var ca=this.dataArray,context=canvas.getContext();context.beginPath();for(var n=0;n<ca.length;n++){var c=ca[n].command;var p=ca[n].points;switch(c){case 'L':context.lineTo(p[0],p[1]);break;case 'M':context.moveTo(p[0],p[1]);break;case 'C':context.bezierCurveTo(p[0],p[1],p[2],p[3],p[4],p[5]);break;case 'Q':context.quadraticCurveTo(p[0],p[1],p[2],p[3]);break;case 'A':var cx=p[0],cy=p[1],rx=p[2],ry=p[3],theta=p[4],dTheta=p[5],psi=p[6],fs=p[7];var r=(rx>ry)?rx:ry;var scaleX=(rx>ry)?1:rx/ry;var scaleY=(rx>ry)?ry/rx:1;context.translate(cx,cy);context.rotate(psi);context.scale(scaleX,scaleY);context.arc(0,0,r,theta,theta+dTheta,1-fs);context.scale(1/scaleX,1/scaleY);context.rotate(-psi);context.translate(-cx,-cy);break;case 'z':context.closePath();break;}}
canvas.fillStroke(this);}};Kinetic.Global.extend(Kinetic.Path,Kinetic.Shape);/**/
Kinetic.Path.getLineLength=function(x1,y1,x2,y2){return Math.sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1));};Kinetic.Path.getPointOnLine=function(dist,P1x,P1y,P2x,P2y,fromX,fromY){if(fromX===undefined){fromX=P1x;}
if(fromY===undefined){fromY=P1y;}
var m=(P2y-P1y)/((P2x-P1x)+0.00000001);var run=Math.sqrt(dist*dist/(1+m*m));if(P2x<P1x)
run*=-1;var rise=m*run;var pt;if((fromY-P1y)/((fromX-P1x)+0.00000001)===m){pt={x:fromX+run,y:fromY+rise};}
else{var ix,iy;var len=this.getLineLength(P1x,P1y,P2x,P2y);if(len<0.00000001){return undefined;}
var u=(((fromX-P1x)*(P2x-P1x))+((fromY-P1y)*(P2y-P1y)));u=u/(len*len);ix=P1x+u*(P2x-P1x);iy=P1y+u*(P2y-P1y);var pRise=this.getLineLength(fromX,fromY,ix,iy);var pRun=Math.sqrt(dist*dist-pRise*pRise);run=Math.sqrt(pRun*pRun/(1+m*m));if(P2x<P1x)
run*=-1;rise=m*run;pt={x:ix+run,y:iy+rise};}
return pt;};Kinetic.Path.getPointOnCubicBezier=function(pct,P1x,P1y,P2x,P2y,P3x,P3y,P4x,P4y){function CB1(t){return t*t*t;}
function CB2(t){return 3*t*t*(1-t);}
function CB3(t){return 3*t*(1-t)*(1-t);}
function CB4(t){return(1-t)*(1-t)*(1-t);}
 var x=P4x*CB1(pct)+P3x*CB2(pct)+P2x*CB3(pct)+P1x*CB4(pct);var y=P4y*CB1(pct)+P3y*CB2(pct)+P2y*CB3(pct)+P1y*CB4(pct);return{x:x,y:y};};Kinetic.Path.getPointOnQuadraticBezier=function(pct,P1x,P1y,P2x,P2y,P3x,P3y){function QB1(t){return t*t;}
function QB2(t){return 2*t*(1-t);}
function QB3(t){return(1-t)*(1-t);}
var x=P3x*QB1(pct)+P2x*QB2(pct)+P1x*QB3(pct);var y=P3y*QB1(pct)+P2y*QB2(pct)+P1y*QB3(pct);return{x:x,y:y};};Kinetic.Path.getPointOnEllipticalArc=function(cx,cy,rx,ry,theta,psi){var cosPsi=Math.cos(psi),sinPsi=Math.sin(psi);var pt={x:rx*Math.cos(theta),y:ry*Math.sin(theta)};return{x:cx+(pt.x*cosPsi-pt.y*sinPsi),y:cy+(pt.x*sinPsi+pt.y*cosPsi)};};Kinetic.Path.parsePathData=function(data){if(!data){return[];}
var cs=data; var cc=['m','M','l','L','v','V','h','H','z','Z','c','C','q','Q','t','T','s','S','a','A'];cs=cs.replace(new RegExp(' ','g'),',');for(var n=0;n<cc.length;n++){cs=cs.replace(new RegExp(cc[n],'g'),'|'+cc[n]);}
var arr=cs.split('|');var ca=[];var cpx=0;var cpy=0;for(var n=1;n<arr.length;n++){var str=arr[n];var c=str.charAt(0);str=str.slice(1);str=str.replace(new RegExp(',-','g'),'-');str=str.replace(new RegExp('-','g'),',-');str=str.replace(new RegExp('e,-','g'),'e-');var p=str.split(',');if(p.length>0&&p[0]===''){p.shift();}
for(var i=0;i<p.length;i++){p[i]=parseFloat(p[i]);}
while(p.length>0){if(isNaN(p[0]))
break;var cmd=null;var points=[];var startX=cpx,startY=cpy;switch(c){case 'l':cpx+=p.shift();cpy+=p.shift();cmd='L';points.push(cpx,cpy);break;case 'L':cpx=p.shift();cpy=p.shift(); points.push(cpx,cpy);break;case 'm':cpx+=p.shift();cpy+=p.shift();cmd='M';points.push(cpx,cpy);c='l';break;case 'M':cpx=p.shift();cpy=p.shift();cmd='M';points.push(cpx,cpy);c='L';break;case 'h':cpx+=p.shift();cmd='L';points.push(cpx,cpy);break;case 'H':cpx=p.shift();cmd='L';points.push(cpx,cpy);break;case 'v':cpy+=p.shift();cmd='L';points.push(cpx,cpy);break;case 'V':cpy=p.shift();cmd='L';points.push(cpx,cpy);break;case 'C':points.push(p.shift(),p.shift(),p.shift(),p.shift());cpx=p.shift();cpy=p.shift();points.push(cpx,cpy);break;case 'c':points.push(cpx+p.shift(),cpy+p.shift(),cpx+p.shift(),cpy+p.shift());cpx+=p.shift(); cpy+=p.shift();cmd='C';points.push(cpx,cpy);break;case 'S':var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='C'){ctlPtx=cpx+(cpx-prevCmd.points[2]);ctlPty=cpy+(cpy-prevCmd.points[3]);}
points.push(ctlPtx,ctlPty,p.shift(),p.shift());cpx=p.shift();cpy=p.shift();cmd='C';points.push(cpx,cpy);break;case 's':var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='C'){ctlPtx=cpx+(cpx-prevCmd.points[2]);ctlPty=cpy+(cpy-prevCmd.points[3]);}
points.push(ctlPtx,ctlPty,cpx+p.shift(),cpy+p.shift());cpx+=p.shift();cpy+=p.shift();cmd='C';points.push(cpx,cpy);break;case 'Q':points.push(p.shift(),p.shift());cpx=p.shift();cpy=p.shift();points.push(cpx,cpy);break;case 'q':points.push(cpx+p.shift(),cpy+p.shift());cpx+=p.shift();cpy+=p.shift();cmd='Q';points.push(cpx,cpy);break;case 'T':var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='Q'){ctlPtx=cpx+(cpx-prevCmd.points[0]);ctlPty=cpy+(cpy-prevCmd.points[1]);}
cpx=p.shift();cpy=p.shift();cmd='Q';points.push(ctlPtx,ctlPty,cpx,cpy);break;case 't':var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='Q'){ ctlPtx=cpx+(cpx-prevCmd.points[0]);ctlPty=cpy+(cpy-prevCmd.points[1]);}
cpx+=p.shift();cpy+=p.shift();cmd='Q';points.push(ctlPtx,ctlPty,cpx,cpy);break;case 'A':var rx=p.shift(),ry=p.shift(),psi=p.shift(),fa=p.shift(),fs=p.shift();var x1=cpx,y1=cpy;cpx=p.shift(),cpy=p.shift();cmd='A';points=this.convertEndpointToCenterParameterization(x1,y1,cpx,cpy,fa,fs,rx,ry,psi);break;case 'a':var rx=p.shift(),ry=p.shift(),psi=p.shift(),fa=p.shift(),fs=p.shift();var x1=cpx,y1=cpy;cpx+=p.shift(),cpy+=p.shift();cmd='A';points=this.convertEndpointToCenterParameterization(x1,y1,cpx,cpy,fa,fs,rx,ry,psi);break;}
ca.push({command:cmd||c,points:points,start:{x:startX,y:startY},pathLength:this.calcLength(startX,startY,cmd||c,points)});}
if(c==='z'||c==='Z'){ca.push({command:'z',points:[],start:undefined,pathLength:0});}}
return ca;};Kinetic.Path.calcLength=function(x,y,cmd,points){var len,p1,p2;var path=Kinetic.Path;switch(cmd){case 'L': return path.getLineLength(x,y,points[0],points[1]);case 'C':len=0.0;p1=path.getPointOnCubicBezier(0,x,y,points[0],points[1],points[2],points[3],points[4],points[5]);for(t=0.01;t<=1;t+=0.01){p2=path.getPointOnCubicBezier(t,x,y,points[0],points[1],points[2],points[3],points[4],points[5]);len+=path.getLineLength(p1.x,p1.y,p2.x,p2.y);p1=p2;}
return len;case 'Q':len=0.0;p1=path.getPointOnQuadraticBezier(0,x,y,points[0],points[1],points[2],points[3]);for(t=0.01;t<=1;t+=0.01){p2=path.getPointOnQuadraticBezier(t,x,y,points[0],points[1],points[2],points[3]);len+=path.getLineLength(p1.x,p1.y,p2.x,p2.y);p1=p2;}
return len;case 'A':len=0.0;var start=points[4];var dTheta=points[5];var end=points[4]+dTheta;var inc=Math.PI/180.0;if(Math.abs(start-end)<inc){inc=Math.abs(start-end);}
p1=path.getPointOnEllipticalArc(points[0],points[1],points[2],points[3],start,0);if(dTheta<0){for(t=start-inc;t>end;t-=inc){ p2=path.getPointOnEllipticalArc(points[0],points[1],points[2],points[3],t,0);len+=path.getLineLength(p1.x,p1.y,p2.x,p2.y);p1=p2;}}
else{for(t=start+inc;t<end;t+=inc){p2=path.getPointOnEllipticalArc(points[0],points[1],points[2],points[3],t,0);len+=path.getLineLength(p1.x,p1.y,p2.x,p2.y);p1=p2;}}
p2=path.getPointOnEllipticalArc(points[0],points[1],points[2],points[3],end,0);len+=path.getLineLength(p1.x,p1.y,p2.x,p2.y);return len;}
return 0;};Kinetic.Path.convertEndpointToCenterParameterization=function(x1,y1,x2,y2,fa,fs,rx,ry,psiDeg){var psi=psiDeg*(Math.PI/180.0);var xp=Math.cos(psi)*(x1-x2)/2.0+Math.sin(psi)*(y1-y2)/2.0;var yp=-1*Math.sin(psi)*(x1-x2)/2.0+Math.cos(psi)*(y1-y2)/2.0;var lambda=(xp*xp)/(rx*rx)+(yp*yp)/(ry*ry);if(lambda>1){rx*=Math.sqrt(lambda);ry*=Math.sqrt(lambda);}
var f=Math.sqrt((((rx*rx)*(ry*ry))-((rx*rx)*(yp*yp))-((ry*ry)*(xp*xp)))/((rx*rx)*(yp*yp)+(ry*ry)*(xp*xp)));if(fa==fs){f*=-1;}
if(isNaN(f)){f=0;}
var cxp=f*rx*yp/ry;var cyp=f*-ry*xp/rx;var cx=(x1+x2)/2.0+Math.cos(psi)*cxp-Math.sin(psi)*cyp;var cy=(y1+y2)/2.0+Math.sin(psi)*cxp+Math.cos(psi)*cyp;var vMag=function(v){return Math.sqrt(v[0]*v[0]+v[1]*v[1]);};var vRatio=function(u,v){return(u[0]*v[0]+u[1]*v[1])/(vMag(u)*vMag(v));};var vAngle=function(u,v){return(u[0]*v[1]<u[1]*v[0]?-1:1)*Math.acos(vRatio(u,v));};var theta=vAngle([1,0],[(xp-cxp)/rx,(yp-cyp)/ry]);var u=[(xp-cxp)/rx,(yp-cyp)/ry];var v=[(-1*xp-cxp)/rx,(-1*yp-cyp)/ry];var dTheta=vAngle(u,v);if(vRatio(u,v)<=-1){dTheta=Math.PI;}
if(vRatio(u,v)>=1){dTheta=0;}
if(fs===0&&dTheta>0){dTheta=dTheta-2*Math.PI;}
if(fs==1&&dTheta<0){dTheta=dTheta+2*Math.PI;}
return[cx,cy,rx,ry,theta,dTheta,psi,fs];};Kinetic.Node.addGettersSetters(Kinetic.Path,['data']);})();(function(){Kinetic.TextPath=function(config){this._initTextPath(config);};Kinetic.TextPath.prototype={_initTextPath:function(config){this.setDefaultAttrs({fontFamily:'Calibri',fontSize:12,fontStyle:'normal',detectionType:'path',text:''});this.dummyCanvas=document.createElement('canvas');this.shapeType="TextPath";this.dataArray=[];var that=this;Kinetic.Shape.call(this,config);this._setDrawFuncs();this.dataArray=Kinetic.Path.parsePathData(this.attrs.data);this.on('dataChange',function(){that.dataArray=Kinetic.Path.parsePathData(this.attrs.data);});var attrs=['text','textStroke','textStrokeWidth'];for(var n=0;n<attrs.length;n++){var attr=attrs[n]; this.on(attr+'Change',that._setTextData);}
that._setTextData();},drawFunc:function(canvas){var charArr=this.charArr,context=canvas.getContext();context.font=this.attrs.fontStyle+' '+this.attrs.fontSize+'pt '+this.attrs.fontFamily;context.textBaseline='middle';context.textAlign='left';context.save();var glyphInfo=this.glyphInfo;for(var i=0;i<glyphInfo.length;i++){context.save();var p0=glyphInfo[i].p0;var p1=glyphInfo[i].p1;var ht=parseFloat(this.attrs.fontSize);context.translate(p0.x,p0.y);context.rotate(glyphInfo[i].rotation);canvas.fillStrokeText(this,glyphInfo[i].text);context.restore();}
context.restore();},getTextWidth:function(){return this.textWidth;},getTextHeight:function(){return this.textHeight;},setText:function(text){Kinetic.Text.prototype.setText.call(this,text);},_getTextSize:function(text){var dummyCanvas=this.dummyCanvas;var context=dummyCanvas.getContext('2d');context.save();context.font=this.attrs.fontStyle+' '+this.attrs.fontSize+'pt '+this.attrs.fontFamily;var metrics=context.measureText(text);context.restore();return{width:metrics.width,height:parseInt(this.attrs.fontSize,10)};},_setTextData:function(){var that=this;var size=this._getTextSize(this.attrs.text);this.textWidth=size.width;this.textHeight=size.height;this.glyphInfo=[];var charArr=this.attrs.text.split('');var p0,p1,pathCmd;var pIndex=-1;var currentT=0;var getNextPathSegment=function(){currentT=0;var pathData=that.dataArray;for(var i=pIndex+1;i<pathData.length;i++){if(pathData[i].pathLength>0){pIndex=i;return pathData[i];}
else if(pathData[i].command=='M'){p0={x:pathData[i].points[0],y:pathData[i].points[1]};}}
return{};};var findSegmentToFitCharacter=function(c,before){var glyphWidth=that._getTextSize(c).width;var currLen=0;var attempts=0;var needNextSegment=false;p1=undefined;while(Math.abs(glyphWidth-currLen)/glyphWidth>0.01&&attempts<25){attempts++;var cumulativePathLength=currLen;while(pathCmd===undefined){pathCmd=getNextPathSegment();if(pathCmd&&cumulativePathLength+pathCmd.pathLength<glyphWidth){cumulativePathLength+=pathCmd.pathLength;pathCmd=undefined;}}
if(pathCmd==={}||p0===undefined)
return undefined;var needNewSegment=false;switch(pathCmd.command){case 'L':if(Kinetic.Path.getLineLength(p0.x,p0.y,pathCmd.points[0],pathCmd.points[1])>glyphWidth){p1=Kinetic.Path.getPointOnLine(glyphWidth,p0.x,p0.y,pathCmd.points[0],pathCmd.points[1],p0.x,p0.y);}
else
pathCmd=undefined;break;case 'A':var start=pathCmd.points[4];var dTheta=pathCmd.points[5];var end=pathCmd.points[4]+dTheta;if(currentT===0)
currentT=start+0.00000001;else if(glyphWidth>currLen)
currentT+=(Math.PI/180.0)*dTheta/Math.abs(dTheta);else
currentT-=Math.PI/360.0*dTheta/Math.abs(dTheta);if(Math.abs(currentT)>Math.abs(end)){currentT=end;needNewSegment=true;}
p1=Kinetic.Path.getPointOnEllipticalArc(pathCmd.points[0],pathCmd.points[1],pathCmd.points[2],pathCmd.points[3],currentT,pathCmd.points[6]);break;case 'C':if(currentT===0){if(glyphWidth>pathCmd.pathLength)
currentT=0.00000001;else
currentT=glyphWidth/pathCmd.pathLength;}
else if(glyphWidth>currLen)
currentT+=(glyphWidth-currLen)/pathCmd.pathLength;else
currentT-=(currLen-glyphWidth)/pathCmd.pathLength;if(currentT>1.0){currentT=1.0;needNewSegment=true;}
p1=Kinetic.Path.getPointOnCubicBezier(currentT,pathCmd.start.x,pathCmd.start.y,pathCmd.points[0],pathCmd.points[1],pathCmd.points[2],pathCmd.points[3],pathCmd.points[4],pathCmd.points[5]);break;case 'Q':if(currentT===0)
currentT=glyphWidth/pathCmd.pathLength;else if(glyphWidth>currLen)
currentT+=(glyphWidth-currLen)/pathCmd.pathLength;else
currentT-=(currLen-glyphWidth)/pathCmd.pathLength;if(currentT>1.0){currentT=1.0;needNewSegment=true;}
p1=Kinetic.Path.getPointOnQuadraticBezier(currentT,pathCmd.start.x,pathCmd.start.y,pathCmd.points[0],pathCmd.points[1],pathCmd.points[2],pathCmd.points[3]);break;}
if(p1!==undefined){currLen=Kinetic.Path.getLineLength(p0.x,p0.y,p1.x,p1.y);}
if(needNewSegment){needNewSegment=false;pathCmd=undefined;}}};for(var i=0;i<charArr.length;i++){//
findSegmentToFitCharacter(charArr[i]);if(p0===undefined||p1===undefined)
break;var width=Kinetic.Path.getLineLength(p0.x,p0.y,p1.x,p1.y);var kern=0;var midpoint=Kinetic.Path.getPointOnLine(kern+width/2.0,p0.x,p0.y,p1.x,p1.y);var rotation=Math.atan2((p1.y-p0.y),(p1.x-p0.x)); this.glyphInfo.push({transposeX:midpoint.x,transposeY:midpoint.y,text:charArr[i],rotation:rotation,p0:p0,p1:p1});p0=p1;}}};Kinetic.Global.extend(Kinetic.TextPath,Kinetic.Shape);Kinetic.Node.addGettersSetters(Kinetic.TextPath,['fontFamily','fontSize','fontStyle','textFill','textStroke','textStrokeWidth']);Kinetic.Node.addGetters(Kinetic.TextPath,['text','textShadow']);Kinetic.TextPath.prototype.setTextShadow=Kinetic.Text.prototype.setTextShadow;Kinetic.TextPath.prototype.fillText=Kinetic.Text.prototype.fillText;Kinetic.TextPath.prototype.strokeText=Kinetic.Text.prototype.strokeText;Kinetic.TextPath.prototype.fillStrokeText=Kinetic.Text.prototype.strokeText;/**/
})();